### ISSUE TITLE
Documentation misleadingly indicates structure coords can be fractions

### ISSUE THREAD

**Issue by mueslo** [materialsproject/pymatgen#1073]
## Summary
The documentation for Structure.from_spacegroup states

> coords (Nx3 array): list of fractional/cartesian coordinates of
>                 each species.

This sounds like it should be possible to initialise them with a list of fractions from the built-in fractions module.

## Example code

```python
from pymatgen.core import Structure
import numpy as np
from fractions import Fraction
Structure.from_spacegroup(139, np.eye(3), ["H"], [[Fraction(1,2), Fraction(1,4), Fraction(0)]])
```

## Error message

```
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    print run.primitive_lattice.reciprocal_lattice.matrix
  File "/home/mueslo/Nextcloud/tmp/fplore/fplore/loader.py", line 306, in primitive_lattice
    return self.primitive_structure.lattice
  File "/home/mueslo/Nextcloud/tmp/fplore/fplore/loader.py", line 302, in primitive_structure
    return self.structure.get_primitive_structure()
  File "/home/mueslo/Nextcloud/tmp/fplore/fplore/loader.py", line 296, in structure
    self.spacegroup_number, self.lattice, elements, coords)
  File "/home/mueslo/.virtualenvs/fplore/lib/python2.7/site-packages/pymatgen/core/structure.py", line 533, in from_spacegroup
    cc = sgp.get_orbit(c, tol=tol)
  File "/home/mueslo/.virtualenvs/fplore/lib/python2.7/site-packages/pymatgen/symmetry/groups.py", line 356, in get_orbit
    pp = np.mod(np.round(pp, decimals=10), 1)
  File "/home/mueslo/.virtualenvs/fplore/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2851, in round_
    return around(a, decimals=decimals, out=out)
  File "/home/mueslo/.virtualenvs/fplore/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2837, in around
    return _wrapfunc(a, 'round', decimals=decimals, out=out)
  File "/home/mueslo/.virtualenvs/fplore/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 62, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/mueslo/.virtualenvs/fplore/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 42, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
AttributeError: 'float' object has no attribute 'rint'
```

**Comment by shyuep** [comment]
fractional coordinates does not mean Fractions, but rather direct coordinates. Nevertheless, I have pushed a fix.
