### ISSUE TITLE
Saving to .mcif fails if oxidation_state is not set

### ISSUE THREAD

**Issue by RoberTnf** [materialsproject/pymatgen#1228]
## System

* Pymatgen version: 2018.7.23
* Python version: 3.6.6
* OS version: Manjaro

## Summary

* Trying to save to .mcif will fail if oxidation_state is not set

## Example code

```python
import pymatgen as mg

s = mg.Structure(mg.Lattice.cubic(4.2), ["Cs", "Cl"],[[0, 0, 0], [0.5, 0.5, 0.5]])a
s.add_spin_by_site([1, -1])
s.to(filename="s.mcif")
```

## Error message

```
# Error message
Traceback (most recent call last):
  File "mcif_test.py", line 5, in <module>
    s.to(filename="s.mcif")
  File "/home/roberto/git/pymatgen/pymatgen/core/structure.py", line 1521, in to
    writer = CifWriter(self, write_magmoms=True)
  File "/home/roberto/git/pymatgen/pymatgen/io/cif.py", line 1216, in __init__
    for el in sorted(comp.elements)])
  File "/home/roberto/git/pymatgen/pymatgen/io/cif.py", line 1216, in <listcomp>
    for el in sorted(comp.elements)])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

## This works
```python
import pymatgen as mg

s = mg.Structure(mg.Lattice.cubic(4.2), ["Cs", "Cl"],[[0, 0, 0], [0.5, 0.5, 0.5]])
s.add_oxidation_state_by_site([1, 1])
s.add_spin_by_site([1, -1])
s.to(filename="s.mcif")
```

## Suggested solution (if any)

* I've already fixed, I will submit a PR

**Comment by mkhorton** [comment]
@RoberTnf Thanks for fixing!

This bug actually comes partly from the fact that in pymatgen we can specify magnetic moments in two different ways: a `magmom` site property, or adding `spin` to `Specie`. So, for your first example, the line `s.add_spin_by_site([1, -1])` could have been replaced by `s.add_site_property('magmom', [1, -1])` and then it would work as intended.

Indeed, it used to be that `oxidation_state` was mandatory for `Specie`,  allowing None (so that we have the ability to only set `spin`) is relatively new, so I suspect there might be a few similar bugs lurking.
