### ISSUE TITLE
pymatgen<=2018.12.12 build broken on fresh python 2.7

### ISSUE THREAD

**Issue by ltalirz** [materialsproject/pymatgen#1520]
**Describe the bug**
The installation of pymatgen <= 2018.12.12 from source is currently broken in fresh python2.7 environments.

I believe the reason is the following:

Since pymatgen includes wheels only for the macos platform, extensions will be built from source on other platforms. pymatgen specifies the build requirement using `setup_requires`, which actually pipes through to `easy_install`
https://github.com/materialsproject/pymatgen/blob/master/setup.py#L91
This line causes `easy_install` to install the latest numpy version available at the time of the build.

`easy_install` is not very picky and will actually install the very latest version of numpy -- even release candidates. The latest numpy release candidate 1.17.0rc1 requires python3.5, which then causes the build of pymatgen to fail.

**To Reproduce**
```
(py27) pip install pymatgen==2018.12.12 --no-binary pymatgen
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pymatgen==2018.12.12
  Using cached https://files.pythonhosted.org/packages/d6/b9/f386300f232c8523f562e39bf07bae0d9c4e6379f423f71df7cd622ddae7/pymatgen-2018.12.12.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/pip-install-aUOCUB/pymatgen/setup.py", line 177, in <module>
        'get_environment = pymatgen.cli.get_environment:main',
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Users/leopold/Applications/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/easy_install-gUdb4m/numpy-1.17.0rc1/setup.py", line 31, in <module>
        self.include_dirs.append(numpy.get_include())
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/pip-install-aUOCUB/pymatgen/
```

**Workaround**
It seems the problem can be solved by manually installing a compatible version of numpy (e.g. `pip install "numpy<1.17"`) *before* installing pymatgen.

**Note:** 
 * This needs to be done in a separate call to pip - `pip install numpy==1.16.4 pymatgen==2018.12.12` [does not work in general](https://travis-ci.org/ltalirz/aiida_core/jobs/553536605#L998).
 * It is important that the version of numpy used to build the pymatgen extensions is the same version of numpy that is present when using pymatgen - otherwise you can run into issues like [these](https://travis-ci.org/aiidateam/aiida_core/jobs/484118664#L1472). When you have packages that require specific numpy versions, it is therefore important to install pymatgen *last*.

**Comment by shyuep** [comment]
Thanks for reporting this, but I am not inclined to issue a fix for this. Newer versions of pymatgen are Py3 only, and other packages like numpy have dropped Py27 support already. From the deprecation message, it seem that pip is going to drop it on Jan 1 2020 as well. So whatever fixes issues is going to be relevant only for the next 5 months.

I recommend that everyone transits to py3 today, rather than continuing to work in Py27. With conda, it is relatively easy to create a py3 env even with Py27 system python.

**Comment by mkhorton** [comment]
Thanks for the write-up @ltalirz, I concur with @shyuep but I will make a note of this in the docs in case any users really need to get this working, and it's a good reminder to be more careful with the setup.py requirements in future.
