### ISSUE TITLE
calling pmg command line interface throws exception when using Python 2.7

### ISSUE THREAD

**Issue by jdagdelen** [materialsproject/pymatgen#1533]
**Describe the bug**
calling pmg command line interface throws exception
**To Reproduce**
1. Install pymatgen for system python (python 2.7)
2. On command line, enter "pmg -h"

**Expected behavior**
pmg cli displays help information. 

**Error Message**
usr/local/lib/python2.7/site-packages/pymatgen/__init__.py:89: UserWarning:
Pymatgen will drop Py2k support from v2019.1.1. Pls consult the documentation
at https://www.pymatgen.org for more details.
  at https://www.pymatgen.org for more details.""")
Traceback (most recent call last):
  File "/usr/local/bin/pmg", line 7, in <module>
    from pymatgen.cli.pmg import main
  File "/usr/local/lib/python2.7/site-packages/pymatgen/cli/pmg.py", line 19, in <module>
    from pymatgen.cli.pmg_plot import plot
  File "/usr/local/lib/python2.7/site-packages/pymatgen/cli/pmg_plot.py", line 13, in <module>
    from pymatgen.analysis.diffraction.xrd import XRDCalculator
  File "/usr/local/lib/python2.7/site-packages/pymatgen/analysis/diffraction/xrd.py", line 15, in <module>
    from .core import DiffractionPattern, DiffractionPatternCalculator, \
  File "/usr/local/lib/python2.7/site-packages/pymatgen/analysis/diffraction/core.py", line 50, in <module>
    class DiffractionPatternCalculator(abc.ABC):
AttributeError: 'module' object has no attribute 'ABC'

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by jdagdelen** [comment]
Pymatgen no longer supports Python 2.X.
