### ISSUE TITLE
ValueError: No POTCAR for C with functional PBE found

### ISSUE THREAD

**Issue by Jaydu1996** [materialsproject/pymatgen#1878]
**Describe the bug**
The pymatgen can't recognize the POTCAR(PBE_52), although I think I have set the correct pmgrc.yaml file.
The bug is 
```
Traceback (most recent call last):
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/fireworks/core/rocket.py", line 262, in run
    m_action = t.run_task(my_spec)
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/atomate/vasp/firetasks/write_inputs.py", line 85, in run_task
    vis.write_input(".", potcar_spec=potcar_spec)
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/sets.py", line 722, in write_input
    zip_output=zip_output
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/sets.py", line 212, in write_input
    vinput = self.get_vasp_input()
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/sets.py", line 174, in get_vasp_input
    potcar=self.potcar,
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/sets.py", line 129, in potcar
    potcar = Potcar(self.potcar_symbols, functional=self.potcar_functional)
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/inputs.py", line 2213, in __init__
    self.set_symbols(symbols, functional, sym_potcar_map)
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/inputs.py", line 2320, in set_symbols
    p = PotcarSingle.from_symbol_and_functional(el, functional)
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/inputs.py", line 1939, in from_symbol_and_functional
    "are using newer psps from VASP." % (symbol, functional)
ValueError: No POTCAR for C with functional PBE found. Please set the PMG_VASP_PSP_DIR environment in .pmgrc.yaml, or you may need to set PMG_DEFAULT_FUNCTIONAL to PBE_52 or PBE_54 if you are using newer psps from VASP.
```
And my .pmgrc.ymal 's content is below:
```
PMG_DEFAULT_FUNCTIONAL: PBE_52
PMG_MAPI_KEY: ****************
PMG_VASP_PSR_DIR: /home/user/pseudopotentials
```
what's the problem with it? How can I solve it

Provide any example files that are needed to reproduce the error, 
especially if the bug pertains to parsing of a file.
```
In [2]: import pymatgen as mg
In [3]: structure = mg.Structure.from_file(‘POSCAR’)
In [4]: structure.composition
Out[4]: Comp: C2
In [5]: from pymatgen.io.vasp.sets import MPStaticSet
In [7]: static = MPStaticSet(structure)
In [8]: static.write_input(output_dir=‘crgete’)
```
**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [2020.4.29]
 - python=3.7.7

**Comment by mkhorton** [comment]
Hi @Jaydu1996, what does your directory structure look like? Your `pseudopotentials` folder should have a `POT_GGA_PAW_PBE_52` folder inside it, and that has the POTCARs gzipped, e.g. `POTCAR.Ac.gz`

**Comment by Jaydu1996** [comment]
The directory structure is below:
```
[user@master POT_GGA_PAW_PBE_52]$ pwd
/home/user/pseudopotentials/POT_GGA_PAW_PBE_52
[user@master POT_GGA_PAW_PBE_52]$ ls
POTCAR.C.gz
[user@master POT_GGA_PAW_PBE_52]$
```

**Comment by mkhorton** [comment]
Hm, perhaps the instructions are out of date, try:

```
static = MPStaticSet(structure, user_potcar_functional='PBE_52')
```

If this works, I think it may be an error [here](https://github.com/materialsproject/pymatgen/blob/c65a6a32f35b345be1a76f6f9bad6f94e1e2cae7/pymatgen/io/vasp/sets.py#L411) with a missing "PMG" prefix.

**Comment by Jaydu1996** [comment]
I have a try, but it doesn't work. But do you have the experience of using atomate. If I use 'rlaunch' to run the job, it will appear the error `ValueError: No POTCAR for C with functional PBE found.`. And if I use 'qlaunch' to run the job, it will appear the error `ModuleNotFoundError: No module named 'atomate'`, and this error is described [here](https://stackoverflow.com/questions/62410345/modulenotfounderror-no-module-named-atomate-but-i-have-install-it) in deatil. But I don't know why. 
```
>>> import pymatgen as mg
>>> structure = mg.Structure.from_file('POSCAR')
>>> structure.composition
Comp: C2
>>> from pymatgen.io.vasp.sets import MPStaticSet
>>> static = MPStaticSet(structure, user_potcar_functional='PBE_52')
/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/sets.py:437: BadInputSetWarning: Overriding the POTCAR functional is generally not recommended  as it significantly affect the results of calculations and compatibility with other calculations done with the same input set. Note that some POTCAR symbols specified in the configuration file may not be available in the selected functional.
  BadInputSetWarning,
>>> static.write_input(output_dir='crgete')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/sets.py", line 722, in write_input
    zip_output=zip_output
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/sets.py", line 212, in write_input
    vinput = self.get_vasp_input()
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/sets.py", line 174, in get_vasp_input
    potcar=self.potcar,
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/sets.py", line 129, in potcar
    potcar = Potcar(self.potcar_symbols, functional=self.potcar_functional)
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/inputs.py", line 2213, in __init__
    self.set_symbols(symbols, functional, sym_potcar_map)
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/inputs.py", line 2320, in set_symbols
    p = PotcarSingle.from_symbol_and_functional(el, functional)
  File "/home/user/app/anaconda3/envs/firework/lib/python3.7/site-packages/pymatgen/io/vasp/inputs.py", line 1939, in from_symbol_and_functional
    "are using newer psps from VASP." % (symbol, functional)
ValueError: No POTCAR for C with functional PBE_52 found. Please set the PMG_VASP_PSP_DIR environment in .pmgrc.yaml, or you may need to set PMG_DEFAULT_FUNCTIONAL to PBE_52 or PBE_54 if you are using newer psps from VASP.
>>> 
```

**Comment by mkhorton** [comment]
`ModuleNotFoundError: No module named 'atomate'`

This suggests an issue with your Python installation, and not related to pymatgen. Try creating a dedicated conda environment, and make sure this environment is _active_ when you try to run qlaunch. http://matsci.org/atomate is a place for atomate questions

**Comment by mkhorton** [comment]
Ah, I see you posted in the atomate forum too, please don't cross-post the same question in multiple places, it just creates work for the moderators, thanks!
