### ISSUE TITLE
undefined symbol: _intel_fast_memcpy

### ISSUE THREAD

**Issue by bbphysics** [materialsproject/pymatgen#1903]
I have tried loading Pymatgen both using intel and gcc at local cluster however the issue still persist.

Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymatgen 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bb6fq/miniconda3/lib/python3.7/site-packages/pymatgen/__init__.py", line 47, in <module>
    from .core.periodic_table import Element, Specie, DummySpecie
  File "/home/bb6fq/miniconda3/lib/python3.7/site-packages/pymatgen/core/__init__.py", line 12, in <module>
    from .structure import Structure, IStructure, Molecule, IMolecule
  File "/home/bb6fq/miniconda3/lib/python3.7/site-packages/pymatgen/core/structure.py", line 31, in <module>
    from pymatgen.core.lattice import Lattice, get_points_in_spheres
  File "/home/bb6fq/miniconda3/lib/python3.7/site-packages/pymatgen/core/lattice.py", line 25, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/bb6fq/miniconda3/lib/python3.7/site-packages/pymatgen/util/coord.py", line 15, in <module>
    from . import coord_cython as cuc
ImportError: /home/bb6fq/miniconda3/lib/python3.7/site-packages/pymatgen/util/coord_cython.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcpy

**Comment by shyuep** [comment]
This is a problem with the gcc mismatch on Linux. Do a `pip install --user --upgrade pymatgen` and it should disappear.

**Comment by mkhorton** [comment]
Since you're running conda, you can also try `conda install -c conda-forge pytmagen` too

**Comment by bbphysics** [comment]
Thanks, Matthew. 
conda install -c conda-forge pymatgen worked for me !!
CentOS release 6.5
