### ISSUE TITLE
ComputedEntry.as_dict() doesn't work with energy_adjustments

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#1971]
**Describe the bug**
`ComputedEntry.as_dict()` doesn't work with `energy_adjustments`

**To Reproduce**
```python
from pymatgen.entries.computed_entries import (
    ComputedEntry,
    ConstantEnergyAdjustment,
    CompositionEnergyAdjustment,
    TemperatureEnergyAdjustment,
    ManualEnergyAdjustment,
)

ealist = [
    ManualEnergyAdjustment(5),
    ConstantEnergyAdjustment(5),
    CompositionEnergyAdjustment(1, 5, uncertainty_per_atom=0, name="Na"),
    TemperatureEnergyAdjustment(0.005, 100, 10, uncertainty_per_degK=0)
]
entry = ComputedEntry("Na5Cl5", 6.9, energy_adjustments=ealist)
entry.as_dict()

```

this gives the error

```bash
Traceback (most recent call last):
  File "/home/reag2/PhD/second-year/pymatgen/dupl_test.py", line 72, in <module>
    entry.as_dict()
  File "/home/reag2/PhD/second-year/pymatgen/pymatgen/entries/computed_entries.py", line 517, in as_dict
    json.dumps(self.energy_adjustments, cls=MontyEncoder)
  File "/home/reag2/anaconda3/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/reag2/anaconda3/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/reag2/anaconda3/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/reag2/anaconda3/lib/python3.7/site-packages/monty/json.py", line 255, in default
    d = o.as_dict()
  File "/home/reag2/anaconda3/lib/python3.7/site-packages/monty/json.py", line 143, in as_dict
    "Unable to automatically determine as_dict "
NotImplementedError: Unable to automatically determine as_dict format from class. MSONAble requires all args to be present as either self.argname or self._argname, and kwargs to be present undera self.kwargs variable to automatically determine the dict format. Alternatively, you can implement both as_dict and from_dict.
```

Tagging authors of relevant code @rkingsbury @mattmcdermott

**Comment by rkingsbury** [comment]
Thank you for reporting this @CompRhys ! Have you tested against the latest master branch? I believe what you are describing is the same bug that we caught and fixed in #1960 , which was just merged a few days ago.

**Comment by rkingsbury** [comment]
For me, using the your code snippet with the latest upstream pymatgen works properly, with the slight modification that the `uncertainty_per_degK` kwarg has been renamed to `uncertainty_per_deg`. I get the following output:

```{'@module': 'pymatgen.entries.computed_entries',
 '@class': 'ComputedEntry',
 'energy': 6.9,
 'composition': defaultdict(float, {'Na': 5.0, 'Cl': 5.0}),
 'energy_adjustments': [{'@module': 'pymatgen.entries.computed_entries',
   '@class': 'ManualEnergyAdjustment',
   '@version': '2020.9.14',
   'value': 5},
  {'@module': 'pymatgen.entries.computed_entries',
   '@class': 'ConstantEnergyAdjustment',
   '@version': '2020.9.14',
   'value': 5,
   'uncertainty': nan,
   'name': 'Constant energy adjustment',
   'cls': {},
   'description': 'Constant energy adjustment'},
  {'@module': 'pymatgen.entries.computed_entries',
   '@class': 'CompositionEnergyAdjustment',
   '@version': '2020.9.14',
   'adj_per_atom': 1,
   'n_atoms': 5,
   'uncertainty_per_atom': 0,
   'name': 'Na',
   'cls': {},
   'description': 'Composition-based energy adjustment'},
  {'@module': 'pymatgen.entries.computed_entries',
   '@class': 'TemperatureEnergyAdjustment',
   '@version': '2020.9.14',
   'adj_per_deg': 0.005,
   'temp': 100,
   'n_atoms': 10,
   'uncertainty_per_deg': 0,
   'name': '',
   'cls': {},
   'description': 'Temperature-based energy adjustment'}],
 'parameters': {},
 'data': {},
 'entry_id': None,
 'correction': 20.0}
```

**Comment by CompRhys** [comment]
@rkingsbury you're totally right I wasn't quite up to date and it now does work! apologies
