### ISSUE TITLE
BSPlotterProjected not work for d orbital

### ISSUE THREAD

**Issue by Yang-YM** [materialsproject/pymatgen#1987]
When I want to plot the projected band structure using `BSPlotterProjected`, I find it not work if the `dictio` has d orbitals. 
It gives the error :

```
C:\ProgramData\Anaconda3\lib\site-packages\pymatgen\electronic_structure\plotter.py:1058: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
\plt.subplot(fig_rows+fig_cols+count)
Traceback (most recent call last):
  File ".\band-dos.py", line 41, in <module>
    pband_fig.get_projected_plots_dots({'S':['d']}, ylim=(-2,4))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymatgen\electronic_structure\plotter.py", line 1088, in get_projected_plots_dots
    markersize=proj[b][str(Spin.up)][i][j][str(el)][o]
KeyError: 'd'
```

According to follow the code, I find the function `get_projections_on_elements_and_orbitals(self, el_orb_spec)` in class `BandStructure` can not return the information of d orbitals. I want to know how to solve it

This is my code
```
bs_run = Vasprun("./vasprun.xml", parse_projected_eigen=True)
bs_data = bs_run.get_band_structure("./KPOINTS",line_mode=True)
pband_fig = BSPlotterProjected(bs=bs_data)
pband_fig.get_projected_plots_dots({'Cu':['d']}, ylim=(-2,4))
plt.savefig('pband_orbital_fig.png',img_format='png',dpi=300)
plt.show()
```

 - OS: Windows
 - Version 2020.10.20

**Comment by fraricci** [comment]
Let me check this
