### ISSUE TITLE
cannot import pymatgen as mg

### ISSUE THREAD

**Issue by frank-lin-liu** [materialsproject/pymatgen#2064]
operating system: Windows 10

I use the command "conda install --channel conda-forge pymatgen" to install pymatgen in Conda Prompt as described in https://pymatgen.org/installation.html. After installation, I run a python script using "python pymatgen_sample.py". In the pymatgen_sample.py, I import pymatgen using "import pymatgen as mg". But I have the following error,

_**Traceback (most recent call last):
  File "pymatgen_sample.py", line 1, in <module>
    import pymatgen as mg
  File "C:\Users\frank\Anaconda3\lib\site-packages\pymatgen\__init__.py", line 56, in <module>
    from .core.composition import Composition  # noqa
  File "C:\Users\frank\Anaconda3\lib\site-packages\pymatgen\core\__init__.py", line 11, in <module>
    from .lattice import Lattice  # noqa
  File "C:\Users\frank\Anaconda3\lib\site-packages\pymatgen\core\lattice.py", line 23, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "C:\Users\frank\Anaconda3\lib\site-packages\pymatgen\util\coord.py", line 17, in <module>
    from . import coord_cython as cuc
  File "pymatgen/util/coord_cython.pyx", line 1, in init pymatgen.util.coord_cython
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject_**

Could you please help me out?

**Comment by shyuep** [comment]
Pls try to install the latest pymatgen released yesterday. I believe it should solve this problem. It has to do with an incompatibility introduced in numpy 1.20.0 but solved in 1.20.1

**Comment by frank-lin-liu** [comment]
Thank you. Pymatgen can be used now.
