### ISSUE TITLE
Scripts require Python2, but use Python3 when pymatgen is installed for 3.x

### ISSUE THREAD

**Issue by ExpHP** [materialsproject/pymatgen#207]
Various scripts in the `scripts` directory (such as `potcar_setup`) do not support Python 3.  However, if pymatgen is installed from source as a Python 3 module via the following command:

    python3 setup.py install

Then the scripts installed to `/usr/local/bin` will begin with `#!/path/to/python3`, causing them to fail when they encounter any old 2.x features:

    $ potcar_setup
        Traceback (most recent call last):
      File "/usr/local/bin/potcar_setup", line 5, in <module>
        pkg_resources.run_script('pymatgen==3.0.13', 'potcar_setup')
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 528, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1394, in run_script
        execfile(script_filename, namespace, namespace)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 55, in execfile
        exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
      File "/usr/local/lib/python3.4/dist-packages/pymatgen-3.0.13-py3.4-linux-x86_64.egg/EGG-INFO/scripts/potcar_setup", line 16, in <module>
        pspdir = raw_input("Please enter full path where the POT_GGA_PAW_PBE, "
    NameError: name 'raw_input' is not defined
    
    $ python2 `which potcar_setup`
    Please enter full path where the POT_GGA_PAW_PBE, etc. subdirs are present. If y
    ou obtained the PSPs directly from VASP, this should typically be the directory
    that you untar the files to :

**Comment by shyuep** [comment]
Thanks for letting me know. I have just pushed a fix for potcar_setup. Is that the only one? I know that pmg works in Py3.


Shyue Ping

On April 12, 2015 at 2:21:35 PM, Michael Lamparski (notifications@github.com) wrote:

Various scripts in the scripts directory (such as potcar_setup) do not support Python 3. However, if pymatgen is installed from source as a Python 3 module via the following command:

python3 setup.py install

Then the scripts installed to /usr/local/bin will begin with #!/path/to/python3, causing them to fail when they encounter any old 2.x features:

$ potcar_setup
    Traceback (most recent call last):
  File "/usr/local/bin/potcar_setup", line 5, in <module>
    pkg_resources.run_script('pymatgen==3.0.13', 'potcar_setup')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 55, in execfile
    exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
  File "/usr/local/lib/python3.4/dist-packages/pymatgen-3.0.13-py3.4-linux-x86_64.egg/EGG-INFO/scripts/potcar_setup", line 16, in <module>
    pspdir = raw_input("Please enter full path where the POT_GGA_PAW_PBE, "
NameError: name 'raw_input' is not defined

**Comment by ExpHP** [comment]
I'm not sure I have the necessary kind of input files to test all of them, but `diff_incar.py` and `feff_input_generation.py` break right off the bat, and `gaussian_analyzer` produces "TypeError: the JSON object must be str, not 'bytes'".

Funny, when I run pmg with Python3, I get this:

    $ pmg
    Traceback (most recent call last):
      File "/usr/local/bin/pmg", line 5, in <module>
        pkg_resources.run_script('pymatgen==3.0.13', 'pmg')
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 528, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 55, in execfile
        exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
      File "/usr/local/lib/python3.4/dist-packages/pymatgen-3.0.13-py3.4-linux-x86_64.egg/EGG-INFO/scripts/pmg", line 514, in <module>
        main()
      File "/usr/local/lib/python3.4/dist-packages/pymatgen-3.0.13-py3.4-linux-x86_64.egg/EGG-INFO/scripts/pmg", line 510, in main
        args.func(args)
    AttributeError: 'Namespace' object has no attribute 'func'

This appears to be related to a post-3.0 change: http://bugs.python.org/issue16308pyton

**Comment by shyuep** [comment]
Ok, I just pushed a fix to test two problems. One of them is a unicode handling issue. the other is a change in the behavior of argparse when no sub parsers are specified. I have implemented workaround for that.


Shyue Ping

On April 12, 2015 at 2:52:48 PM, Michael Lamparski (notifications@github.com) wrote:

I'm not sure I have the necessary kind of input files to test all of them, but diff_incar.py and feff_input_generation.py break right off the bat, and gaussian_analyzer produces "TypeError: the JSON object must be str, not 'bytes'".

Funny, when I run pmg with Python3, I get this:

$ pmg
Traceback (most recent call last):
  File "/usr/local/bin/pmg", line 5, in <module>
    pkg_resources.run_script('pymatgen==3.0.13', 'pmg')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1394, in run_script
execfile(script_filename, namespace, namespace)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 55, in execfile
    exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
  File "/usr/local/lib/python3.4/dist-packages/pymatgen-3.0.13-py3.4-linux-x86_64.egg/EGG-INFO/scripts/pmg", line 514, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/pymatgen-3.0.13-py3.4-linux-x86_64.egg/EGG-INFO/scripts/pmg", line 510, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'

This appears to be related to a post-3.0 change: http://bugs.python.org/issue16308pyton
