### ISSUE TITLE
Tests fail:  invalid module name: 'pymatgen.io.vasp.inputs'

### ISSUE THREAD

**Issue by yurivict** [materialsproject/pymatgen#2275]
**Describe the bug**
```python-3.8 -m pytest``` fails:

```
===>   py38-pymatgen-2022.0.15 depends on file: /usr/local/bin/python3.8 - found
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/_pytest/warnings.py", line 150, in pytest_collection
INTERNALERROR>     with catch_warnings_for_item(
INTERNALERROR>   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/_pytest/warnings.py", line 88, in catch_warnings_for_item
INTERNALERROR>     _setoption(warnings, arg)
INTERNALERROR>   File "/usr/local/lib/python3.8/site-packages/_pytest/warnings.py", line 27, in _setoption
INTERNALERROR>     category = wmod._getcategory(category)
INTERNALERROR>   File "/usr/local/lib/python3.8/warnings.py", line 262, in _getcategory
INTERNALERROR>     raise _OptionError("invalid module name: %r" % (module,)) from None
INTERNALERROR> warnings._OptionError: invalid module name: 'pymatgen.io.vasp.inputs'

no tests ran in 0.45 seconds
*** Error code 3
```

FreeBSD 13

**Comment by AMDmi3** [comment]
> Please be specific about what data is missing from the distribution

The exhaustive log was attached, the files were mentioned right there. For instance,
- test_files/boltztrap2/vasprun.xml
- test_files/vasprun.xml
- test_files/spectrum_test/LiCoO2_k_xanes.json

> Note that the test files are deliberately not included within the usual pymatgen distribution. The test dir alone is several GB

This is understandable, but in this case not skipping tests if data files required for them are missing is the problem.

**Comment by shyuep** [comment]
For a code like pymatgen, most of the tests involve an external file of some sort. If we skip all tests that require things in test_files, we will be left with a tiny fraction of the code being tested.

As I said before, testing is meant to be done from the Github full repository, which includes the test files. It is not meant to be done from the distributed wheels or the tar.gz source.

**Comment by shyuep** [comment]
The tests were never included in the distribution. Go ahead and download the tar.gz from https://pypi.org/project/pymatgen/ and see for yourself. Pretty sure there are no tests in there.
