### ISSUE TITLE
SpacegroupAnalyzer init failing

### ISSUE THREAD

**Issue by mbkumar** [materialsproject/pymatgen#229]
Hello Shyue,

I am getting the following error when trying to use SpacegroupAnalyzer.

Traceback (most recent call last):
 File "BaBrF_vacancy_scaling.py", line 9, in <module>
    vac = Vacancy(uc, {}, {})
  File "/Users/mbkumar/Research/Defects/pymatgen/pymatgen/analysis/defects/point_defects.py", line 284, in __init__
    symm_finder = SpacegroupAnalyzer(self._structure)
  File "/Users/mbkumar/Research/Defects/pymatgen/pymatgen/symmetry/analyzer.py", line 125, in __init__
    dataset['hall'] = dataset['hall'].strip()
AttributeError: 'list' object has no attribute 'strip'

**Comment by shyuep** [comment]
You have an old spglib? Try doing python setup.py develop again first. 


Shyue Ping

On August 13, 2015 at 12:25:59, Bharat Medasani (notifications@github.com) wrote:

Hello Shyue,

I am getting the following error when trying to use SpacegroupAnalyzer.

Traceback (most recent call last):
File "BaBrF_vacancy_scaling.py", line 9, in
vac = Vacancy(uc, {}, {})
File "/Users/mbkumar/Research/Defects/pymatgen/pymatgen/analysis/defects/point_defects.py", line 284, in init
symm_finder = SpacegroupAnalyzer(self.structure)
File "/Users/mbkumar/Research/Defects/pymatgen/pymatgen/symmetry/analyzer.py", line 125, in __init_
dataset['hall'] = dataset['hall'].strip()
AttributeError: 'list' object has no attribute 'strip'

**Comment by mbkumar** [comment]
Thanks.
