### ISSUE TITLE
pmg config  CLI fails

### ISSUE THREAD

**Issue by ad1v7** [materialsproject/pymatgen#2373]
**Describe the bug**
Cannot configure POTCAR setup as "pmg config" fails to add keywords to .pmgrc.yaml

**To Reproduce**
Fresh install with conda:
$ conda create --name my_pmg python=3.8
$ conda activate my_pmg
$ conda install -c conda-forge pymatgen

run "pmg config --add", for example:

pmg config --add PMG_DEFAULT_FUNCTIONAL PBE_52

throws error:

(pmg2) s1351949@SCE-SOPA-00584:~/TEMP/VASP$ pmg config --add PMG_DEFAULT_FUNCTIONAL PBE_52
Traceback (most recent call last):
  File "/home/s1351949/miniconda3/envs/pmg2/bin/pmg", line 11, in <module>
    sys.exit(main())
  File "/home/s1351949/miniconda3/envs/pmg2/lib/python3.8/site-packages/pymatgen/cli/pmg.py", line 297, in main
    args.func(args)
  File "/home/s1351949/miniconda3/envs/pmg2/lib/python3.8/site-packages/pymatgen/cli/pmg_config.py", line 217, in configure_pmg
    add_config_var(args)
  File "/home/s1351949/miniconda3/envs/pmg2/lib/python3.8/site-packages/pymatgen/cli/pmg_config.py", line 202, in add_config_var
    dumpfn(d, SETTINGS_FILE, default_flow_style=False)
  File "/home/s1351949/miniconda3/envs/pmg2/lib/python3.8/site-packages/monty/serialization.py", line 119, in dumpfn
    yaml.dump(obj, fp, *args, **kwargs)
TypeError: dump() got an unexpected keyword argument 'default_flow_style'

**Expected behavior**
Add PMG_DEFAULT_FUNCTIONAL keyword to .pmgrc.yaml file

**Desktop (please complete the following information):**
 - OS:Linux
 - Python 3.8.12
 - fresh conda environment for pmg

**Comment by shyuep** [comment]
Thanks for reporting this. This is due to a recent change in the way yaml files are handled in ruamel.yaml. 
I just fixed it in the code.
