### ISSUE TITLE
Empty `.pmgrc.yaml` file produces error with `yaml.safe_load` (or `yaml.load`) and `update`

### ISSUE THREAD

**Issue by sgbaird** [materialsproject/pymatgen#2377]
The bug in https://github.com/materialsproject/pymatgen/issues/2373 seems to produce an empty `.pmgrc.yaml` configuration file for me
```python
Traceback (most recent call last):
  File "/usr/local/bin/pmg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pymatgen/cli/pmg.py", line 440, in main
    return args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/pymatgen/cli/pmg_config.py", line 218, in configure_pmg
    add_config_var(args)
  File "/usr/local/lib/python3.7/dist-packages/pymatgen/cli/pmg_config.py", line 203, in add_config_var
    dumpfn(d, SETTINGS_FILE, default_flow_style=False)
  File "/usr/local/lib/python3.7/dist-packages/monty/serialization.py", line 119, in dumpfn
    yaml.dump(obj, fp, *args, **kwargs)
TypeError: dump() got an unexpected keyword argument 'default_flow_style'
```

After using the fallback of `export PMG_MAPI_KEY={MP_API_KEY}`, an error is later produced when trying to load the empty config file:
```python
from pymatgen.core import Composition
```

```python
/usr/local/lib/python3.7/dist-packages/pymatgen/core/__init__.py in <module>()
     59 
     60 
---> 61 SETTINGS = _load_pmg_settings()
     62 locals().update(SETTINGS)

/usr/local/lib/python3.7/dist-packages/pymatgen/core/__init__.py in _load_pmg_settings()
     49         with open(SETTINGS_FILE) as f:
     50             d_yml = yaml.safe_load(f)
---> 51         d.update(d_yml)
     52     except OSError:
     53         # If there are any errors, default to using environment variables

TypeError: 'NoneType' object is not iterable
```

The workaround is to delete the empty file, and only use the `export` command above or use the [latest changes](https://github.com/materialsproject/pymatgen/issues/2373#issuecomment-1020151373) (which I'm sure will go into a new release soon), or to make the empty file read:
```yaml
PMG_MAPI_KEY: <my-api-key>
```

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sparks-baird/piro/blob/main/piro/notebooks/BaTiO3-Example-Colab.ipynb)

`pymatgen` version is `2022.0.17`.

**Comment by shyuep** [comment]
I already fixed it in the latest release. BUt if your pymatgen is 2022.0.17, that is the old version.

**Comment by SamWangGibhub** [comment]
Hi,
I have a similar problem:
when enter: pmg config --add PMG_VASP_PSP_DIR /home/myname/PYMATGEN_POTCAR/POT_GGA_PAW_PBE/
error:
**Existing /home/myname/.pmgrc.yaml backed up to /home/linwen/.pmgrc.yaml.bak
Traceback (most recent call last):
  File "/home/myname/anaconda3/envs/vasp_highThroughComputer/bin/pmg", line 11, in <module>
    sys.exit(main())
  File "/home/myname/anaconda3/envs/vasp_highThroughComputer/lib/python3.7/site-packages/pymatgen/cli/pmg.py", line 440, in main
    return args.func(args)
  File "/home/myname/anaconda3/envs/vasp_highThroughComputer/lib/python3.7/site-packages/pymatgen/cli/pmg_config.py", line 218, in configure_pmg
    add_config_var(args)
  File "/home/myname/anaconda3/envs/vasp_highThroughComputer/lib/python3.7/site-packages/pymatgen/cli/pmg_config.py", line 203, in add_config_var
    dumpfn(d, SETTINGS_FILE, default_flow_style=False)
  File "/home/myname/anaconda3/envs/vasp_highThroughComputer/lib/python3.7/site-packages/monty/serialization.py", line 119, in dumpfn
    yaml.dump(obj, fp, *args, **kwargs)
TypeError: dump() got an unexpected keyword argument 'default_flow_style'**

**Comment by shyuep** [comment]
As noted above, please upgrade your pymatgen to the latest version.

**Comment by SamWangGibhub** [comment]
I have installed pymatgen with "conda install pymatgen"
Then, conda update pymatgen
But, conda list
My postman's version is pymatgen-2022.0.17
How to update pymatgen to the latest version?

**Comment by shyuep** [comment]
You are on py37. That the latest version for that python version. I suggest you go to py38 or 39. Py37 is very old.

**Comment by SamWangGibhub** [comment]
> You are on py37. That the latest version for that python version. I suggest you go to py38 or 39. Py37 is very old.

Thank you for your reply.
It works.
