### ISSUE TITLE
"infinite" loop when importing pymatgen.core and MPRester

### ISSUE THREAD

**Issue by ancarnevali** [materialsproject/pymatgen#2412]
## Bug description
The commands `import pymatgen.core` and `from pymatgen.ext.matproj import MPRester` are not completed, but result in a loop between two lines. Here follows the traceback after I interrupt the run with ctrl+c:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\anton\anaconda3\envs\pymat\lib\site-packages\pymatgen\core\__init__.py", line 54, in <module>
    SETTINGS = _load_pmg_settings()
  File "C:\Users\anton\anaconda3\envs\pymat\lib\site-packages\pymatgen\core\__init__.py", line 43, in _load_pmg_settings
    d_yml = yaml.load(f)
  File "C:\Users\anton\anaconda3\envs\pymat\lib\site-packages\ruamel\yaml\main.py", line 343, in load
    return constructor.get_single_data()
  File "C:\Users\anton\anaconda3\envs\pymat\lib\site-packages\ruamel\yaml\constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "C:\Users\anton\anaconda3\envs\pymat\lib\site-packages\ruamel\yaml\composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "C:\Users\anton\anaconda3\envs\pymat\lib\site-packages\ruamel\yaml\composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\anton\anaconda3\envs\pymat\lib\site-packages\ruamel\yaml\composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\anton\anaconda3\envs\pymat\lib\site-packages\ruamel\yaml\composer.py", line 218, in compose_mapping_node
```
where the last two lines (138 and 218) are repeated for a number of times, until run interruption by ctrl+c.

## To Reproduce
The error appeared in the following cases:
1) fresh installation of miniconda3
1.1) new virtual environment where I run `conda install -c anaconda ipykernel` followed by `conda install --channel conda-forge pymatgen`
1.2) new virtual environment where I run `conda install -c anaconda ipykernel` followed by c`onda install --yes numpy scipy matplotlib` and `pip install pymatgen`
1.2.1) same happens if I `conda update ruamel.yaml`, which appears to be the problematic package (see the traceback above).

2) Same on anaconda3.

I tried python 3.9.7 and 3.10.2

## Expected behavior
Just import pymatgen's modules

## Operating system
OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
System Type	x64-based PC

Any help would be very welcome!

**Comment by shyuep** [comment]
I can't reproduce this. Can you try renaming your .pmgrc.yaml file to sometjing else (e.g., .pmgrc.yaml.bak) and see if this still recurs. You can also try downgrading ruamel.yaml and see if that helps.

**Comment by ancarnevali** [comment]
Thank you so much, renaming pmgrc.yaml worked! Why though?

**Comment by shyuep** [comment]
Probably means your .pmgrc.yaml was corrupted in some way and caused the parser to trip up. You will need to reconfigure it though if you plan to use psuedopotentials or the MPRester.

**Comment by ancarnevali** [comment]
I tried launching a query with MPRester and it appears to work. It automatically generated a new pmgrc.yaml. The older one has a crazy volume of 3.9 Gb, is it something expected?

**Comment by shyuep** [comment]
No. That is a config yaml file. It should a less than 1kb. Pls delete that old corrupted file.
