### ISSUE TITLE
`ChemicalPotentialDiagram` fails on interior point selection for some systems

### ISSUE THREAD

**Issue by mattmcdermott** [materialsproject/pymatgen#2445]
**Describe the bug**
The `ChemicalPotentialDiagram` class currently fails upon initialization for some systems using MP data (e.g., Zr-O-N) due to improper selection of an interior point to be passed to Qhull.

The current logic implemented in pymatgen is to use the mean of the elemental limits/bounds as the interior point, however, it would be just as easy to use the minimum (or some offset from the minimum). 

**To Reproduce**
```python
with MPRester() as mpr:
    entries = mpr.get_entries_in_chemsys("Zr-O-N")
cpd = ChemicalPotentialDiagram(entries)
```

**Expected behavior**
The interior point is always selected logically, such that it never leads to a Qhull error.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 2022.2.10

**Additional context**
I have implemented a fix and will address soon!

**Comment by mattmcdermott** [comment]
Just for posterity, here is a copy of the kind of error that is produced in Qhull when selecting an incorrect interior point (Zr-O-N system as before, with `default_min_limit=-20`)

```
scipy.spatial._qhull.QhullError: QH6023 qhull input error: feasible point is not clearly inside halfspace
feasible point:    -10    -10 
     halfspace:    0.5    0.5 
     at offset: 10.012997585  and distance: 0.01299758500000081 
The halfspace was at index 0

While executing:  | qhull H 
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 961326389  Halfspace  _maxoutside  0

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/flask/helpers.py", line 36, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/flask/helpers.py", line 25, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/flask/patch.py", line 494, in _traced_request
    return wrapped(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/.local/lib/python3.9/site-packages/ddtrace/contrib/flask/wrappers.py", line 25, in trace_func
    return wrapped(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/dash/dash.py", line 1344, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/root/.local/lib/python3.9/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/app/mp_web/apps/phasediagram/phasediagram.py", line 353, in update_table
    chempot_fig = chempot_diagram.get_plot()
  File "/root/.local/lib/python3.9/site-packages/pymatgen/analysis/chempot_diagram.py", line 150, in get_plot
    fig = self._get_2d_plot(elements=elems, label_stable=label_stable)
  File "/root/.local/lib/python3.9/site-packages/pymatgen/analysis/chempot_diagram.py", line 228, in _get_2d_plot
    domains = self.domains.copy()
  File "/root/.local/lib/python3.9/site-packages/pymatgen/analysis/chempot_diagram.py", line 509, in domains
    return self._get_domains()
  File "/root/.local/lib/python3.9/site-packages/pymatgen/analysis/chempot_diagram.py", line 179, in _get_domains
    hs_int = HalfspaceIntersection(hs_hyperplanes, np.array(interior_point))
  File "_qhull.pyx", line 2813, in scipy.spatial._qhull.HalfspaceIntersection.__init__
  File "_qhull.pyx", line 357, in scipy.spatial._qhull._Qhull.__init__
scipy.spatial._qhull.QhullError: QH6023 qhull input error: feasible point is not clearly inside halfspace
feasible point:    -10    -10 
     halfspace:    0.5    0.5 
     at offset: 10.012997585  and distance: 0.01299758500000081 
The halfspace was at index 0

While executing:  | qhull H 
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 961326389  Halfspace  _maxoutside  0
```

**Comment by mattmcdermott** [comment]
Closing with c70ca529586d848134c2e0e4d9362a0e37d1fdde
