### ISSUE TITLE
bug report on macOS with python3.7

### ISSUE THREAD

**Issue by usccolumbia** [materialsproject/pymatgen#2459]
**Describe the bug**
I have an issue to. import the Composition module when installing latest pymatgen on a macOS using conda with python3.7
it takes long time to import and finally failed and get this error :

Successfully installed future-0.18.2 plotly-5.6.0 pymatgen-2022.0.17 ruamel.yaml-0.17.21 tenacity-8.0.1 uncertainties-3.1.6
(mat) jason$ python convert2formula.py --input oqmd_com_ckpt4049.txt 
Traceback (most recent call last):
  File "convert2formula.py", line 8, in <module>
    from pymatgen.core.composition import Composition
  File "/Users/jason/opt/anaconda3/envs/mat/lib/python3.7/site-packages/pymatgen/core/__init__.py", line 61, in <module>
    SETTINGS = _load_pmg_settings()
  File "/Users/jason/opt/anaconda3/envs/mat/lib/python3.7/site-packages/pymatgen/core/__init__.py", line 50, in _load_pmg_settings
    d_yml = yaml.safe_load(f)
  File "/Users/jason/opt/anaconda3/envs/mat/lib/python3.7/site-packages/ruamel/yaml/main.py", line 1118, in safe_load
    return load(stream, SafeLoader, version)
  File "/Users/jason/opt/anaconda3/envs/mat/lib/python3.7/site-packages/ruamel/yaml/main.py", line 1071, in load
    return loader._constructor.get_single_data()
  File "/Users/jason/opt/anaconda3/envs/mat/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 121, in get_single_data
    return self.construct_document(node)
  File "/Users/jason/opt/anaconda3/envs/mat/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 126, in construct_document
    data = self.construct_object(node)
  File "/Users/jason/opt/anaconda3/envs/mat/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/Users/jason/opt/anaconda3/envs/mat/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 189, in construct_non_recursive_object
    data = constructor(self, node)
  File "/Users/jason/opt/anaconda3/envs/mat/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 696, in construct_undefined
    node.start_mark,
ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:ruamel.yaml.comments.CommentedMap'
  in "/Users/jason/.pmgrc.yaml", line 1, column 1

**To Reproduce**

Provide any example files that are needed to reproduce the error,
especially if the bug pertains to parsing of a file.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac latest version
 - Version Montery M1 Max 

**Additional context**

**Comment by shyuep** [comment]
Pls delete your .pmgrc file and try again.

**Comment by usccolumbia** [comment]
it works like a charm. Thanks. Dr. Ong.  
It bothered me for 2 weeks...
