### ISSUE TITLE
Circular import when importing SpaceGroup

### ISSUE THREAD

**Issue by jacksund** [materialsproject/pymatgen#2470]
**Describe the bug**
The most recent release (2022.3.22) introduced a circular import error the SpaceGroup class

**To Reproduce**
Running the line... 
``` python
from pymatgen.symmetry.groups import SpaceGroup
```
...produces the following error...
``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jacks\anaconda3\envs\pmg_env\lib\site-packages\pymatgen\symmetry\groups.py", line 25, in <module>
    from pymatgen.core.lattice import Lattice
  File "C:\Users\jacks\anaconda3\envs\pmg_env\lib\site-packages\pymatgen\core\__init__.py", line 19, in <module>
    from .structure import IMolecule, IStructure, Molecule, Structure
  File "C:\Users\jacks\anaconda3\envs\pmg_env\lib\site-packages\pymatgen\core\structure.py", line 51, in <module>
    from pymatgen.symmetry.maggroups import MagneticSpaceGroup
  File "C:\Users\jacks\anaconda3\envs\pmg_env\lib\site-packages\pymatgen\symmetry\maggroups.py", line 19, in <module>
    from pymatgen.symmetry.groups import SymmetryGroup, in_array_list
ImportError: cannot import name 'SymmetryGroup' from partially initialized module 'pymatgen.symmetry.groups' (most likely due to a circular import) (C:\Users\jacks\anaconda3\envs\pmg_env\lib\site-packages\pymatgen\symmetry\groups.py)
```

**Additional context**

The bug was accidentally introduced by @janosh in this commit: https://github.com/materialsproject/pymatgen/commit/2a0ed0e2df6d6e151e54695997071bef0a43d66f

Looks like the issue is with line 25 (`from pymatgen.core.lattice import Lattice`) which produces the circular import.

**Comment by mkhorton** [comment]
Glad to learn about `typing.TYPE_CHECKING` though, that was new to me! Seems useful
