### ISSUE TITLE
Error when importing mp_api.client 

### ISSUE THREAD

**Issue by lrodrz** [materialsproject/pymatgen#2705]
**Describe the bug**
For some reason when I import `mp_api.client`  I get the following error 

**To Reproduce**
1. create new virtual environment and install mp-api the one that pip got was `mp_api-0.29.3-py3-none-any.whl (69 kB)`
2. run `python` the version I'm using is `Python 3.10.6`
3. `import mp_api.client`

```
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mp_api.client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/my/local/dir/venv/lib/python3.10/site-packages/mp_api/client/__init__.py", line 4, in <module>
    from .mprester import MPRester
  File "/home/my/local/dir/venv/lib/python3.10/site-packages/mp_api/client/mprester.py", line 8, in <module>
    from emmet.core.electronic_structure import BSPathType
  File "/home/my/local/dir/venv/lib/python3.10/site-packages/emmet/core/electronic_structure.py", line 11, in <module>
    from pymatgen.analysis.magnetism.analyzer import (
  File "/home/my/local/dir/venv/lib/python3.10/site-packages/pymatgen/analysis/magnetism/__init__.py", line 8, in <module>
    from pymatgen.analysis.magnetism.analyzer import (
  File "/home/my/local/dir/venv/lib/python3.10/site-packages/pymatgen/analysis/magnetism/analyzer.py", line 23, in <module>
    from pymatgen.core.structure import DummySpecies, Element, Species, Structure
  File "/home/my/local/dir/venv/lib/python3.10/site-packages/pymatgen/core/__init__.py", line 66, in <module>
    locals().update(SETTINGS)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
>>> 
```

The same exact thing happens when I try to use `from mp_api.client import MPRester` which is how I originally ran into this issue. 

**Desktop :**

This is on WSL2 Ubuntu 20.04. I ran this over both VScode and terminal and got the same exact errors. Fresh installations.

**Comment by lrodrz** [comment]
Downgrading python, pymatgen, and mp-api to the following using conda worked. 
`python=3.9.13`
`mp-api=0.29.1`
`pymatgen=2022.9.21`

I get the following error instead. (I know I need to set up that .yaml file 😅) 

```
/my/dir/miniconda3/envs/venv/lib/python3.9/site-packages/pymatgen/core/__init__.py:51: UserWarning: Error loading .pmgrc.yaml: dictionary update sequence element #0 has length 1; 2 is required. You may need to reconfigure your yaml file.
  warnings.warn(f"Error loading .pmgrc.yaml: {ex}. You may need to reconfigure your yaml file.")
/my/dir/miniconda3/envs/venv/lib/python3.9/site-packages/pymatgen/analysis/phase_diagram.py:26: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
```

**Comment by janosh** [comment]
Could you try `pip install pymatgen==2022.10.22` and report if that also raises `ValueError` or just issues a warning?

**Comment by lrodrz** [comment]
> Could you try `pip install pymatgen==2022.10.22` and report if that also raises `ValueError` or just issues a warning?

Yeah the same problem happens..
@janosh 

```
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mp_api.client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/your/favorite/directory/lib/python3.8/site-packages/mp_api/client/__init__.py", line 4, in <module>
    from .mprester import MPRester
  File "/home/your/favorite/directory/lib/python3.8/site-packages/mp_api/client/mprester.py", line 9, in <module>
    from emmet.core.electronic_structure import BSPathType
  File "/home/your/favorite/directory/lib/python3.8/site-packages/emmet/core/electronic_structure.py", line 11, in <module>
    from pymatgen.analysis.magnetism.analyzer import (
  File "/home/your/favorite/directory/lib/python3.8/site-packages/pymatgen/analysis/magnetism/__init__.py", line 8, in <module>
    from pymatgen.analysis.magnetism.analyzer import (
  File "/home/your/favorite/directory/lib/python3.8/site-packages/pymatgen/analysis/magnetism/analyzer.py", line 23, in <module>
    from pymatgen.core.structure import DummySpecies, Element, Species, Structure
  File "/home/your/favorite/directory/lib/python3.8/site-packages/pymatgen/core/__init__.py", line 66, in <module>
    locals().update(SETTINGS)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
>>> 
```

**Comment by janosh** [comment]
> I get the following error instead. (I know I need to set up that .yaml file 😅)

I think that file must already be present on your machine but not in the expected format. If you had no `~/.config/.pmgrc.yaml` or `~/.pmgrc.yaml` file, there should be no error. Can you look for a file in both places and post the content here if you find one?

**Comment by wladerer** [comment]
I had the same issue. I accidentally had 

`PMG_VASP_PSP_DIR = ~/Documents/my_psp`

instead of 

`PMG_VASP_PSP_DIR: ~/Documents/my_psp`

in my ~/.pmgrc.yaml

**Comment by janosh** [comment]
@wladerer Thanks for reporting. Closing this as syntax error requiring user fix.

**Comment by lrodrz** [comment]
> > I get the following error instead. (I know I need to set up that .yaml file 😅)
> 
> I think that file must already be present on your machine but not in the expected format. If you had no `~/.config/.pmgrc.yaml` or `~/.pmgrc.yaml` file, there should be no error. Can you look for a file in both places and post the content here if you find one?

Just commenting here for posterity. 

I had this issue again when i used `pip install mp-api`  in a new conda environment so i came back to this issue and i found  `~/.pmgrc.yaml` in that directory so i deleted it and `from mp_api.client import MPRester` worked. 

Thank you.
