### ISSUE TITLE
Issue with Trajectory.extend()

### ISSUE THREAD

**Issue by sylviancadars** [materialsproject/pymatgen#2718]
Dear pymatgen developpers,

I am facing an issue with the extend() method of Trajectory instances created from Vasprun.to_trajectory().
Attached below is a tests containing three subsequent MD runs conducted on Si, and a script (test_traj_extend.py) designed to extract and concatenate trajectories with pymatgen.

[Si_MD_2022-11-03.tar.gz](https://github.com/materialsproject/pymatgen/files/9927188/Si_MD_2022-11-03.tar.gz)

test_traj_extend.py script:
```
import os
from pymatgen import core
from pymatgen.io.vasp import Vasprun

print('pymatgen core version {}'.format(core.__version__))

root_dir = os.getcwd()
dir_names = [os.path.join(root_dir, dir_name) for dir_name in
             [d for d in os.listdir(root_dir) if os.path.isdir(d)]]

trajectories = []
for dir_name in dir_names:
    file_name = os.path.join(dir_name, 'vasprun.xml')
    vr = Vasprun(file_name)
    trajectories.append(vr.get_trajectory())
    print('trajectories[{}] with length {} created from file {}.'.format(
        len(trajectories)-1, len(trajectories[-1]), file_name))

extended_traj = trajectories[0]
for traj in trajectories[1:]:
    extended_traj.extend(traj)

print('extended_traj of length {}.'.format(extended_traj))
```

I obtain the following error:

```
(base) cadarp02@escs-215-02:/data/VASP/tests/Si_MD_2022-11-03$ python test_traj_extend.py
pymatgen core version 2022.01.09
/home/cadarp02/.local/lib/python3.8/site-packages/pymatgen/io/vasp/outputs.py:383: UnconvergedVASPWarning: /data/VASP/tests/Si_MD_2022-11-03/622432/vasprun.xml is an unconverged VASP run.
Electronic convergence reached: True.
Ionic convergence reached: False.
  warnings.warn(msg, UnconvergedVASPWarning)
trajectories[0] with length 100 created from file /data/VASP/tests/Si_MD_2022-11-03/622432/vasprun.xml.
/home/cadarp02/.local/lib/python3.8/site-packages/pymatgen/io/vasp/outputs.py:383: UnconvergedVASPWarning: /data/VASP/tests/Si_MD_2022-11-03/622360/vasprun.xml is an unconverged VASP run.
Electronic convergence reached: True.
Ionic convergence reached: False.
  warnings.warn(msg, UnconvergedVASPWarning)
trajectories[1] with length 100 created from file /data/VASP/tests/Si_MD_2022-11-03/622360/vasprun.xml.
/home/cadarp02/.local/lib/python3.8/site-packages/pymatgen/io/vasp/outputs.py:383: UnconvergedVASPWarning: /data/VASP/tests/Si_MD_2022-11-03/622216/vasprun.xml is an unconverged VASP run.
Electronic convergence reached: True.
Ionic convergence reached: False.
  warnings.warn(msg, UnconvergedVASPWarning)
trajectories[2] with length 100 created from file /data/VASP/tests/Si_MD_2022-11-03/622216/vasprun.xml.
Traceback (most recent call last):
  File "test_traj_extend.py", line 21, in <module>
    extended_traj.extend(traj)
  File "/home/cadarp02/.local/lib/python3.8/site-packages/pymatgen/core/trajectory.py", line 177, in extend
    self.lattice, self.constant_lattice = self._combine_lattice(
  File "/home/cadarp02/.local/lib/python3.8/site-packages/pymatgen/core/trajectory.py", line 392, in _combine_lattice
    attribute.extend([attr_2.copy()] * len_2 if isinstance(attr_2, list) else attr_2.copy())
AttributeError: 'numpy.ndarray' object has no attribute 'extend'
```
Can you please help me figure out what I may have done wrong and/or solve the problem ?
Thank you very much.
Best wishes.

Sylvian.

**Comment by sylviancadars** [comment]
My intuition is that that there may have been a change in the format (numpy.darray of shape `(steps, 3, 3)` vs list of numpy.ndarrays of shape (3, 3)) of the lattice property that the to_trajectory() method of Vasprun or the Trajectory.extend() function(s) may not have followed, or the opposite. Does this make sense ?

**Comment by sylviancadars** [comment]
In fact the 'solution' described above did not work (it gave me an extended_traj lattice of length 400) and should definitely be diregarded.

I think I finally got the real solution. The problem was in the Trajectory._combine_lattice() method, which should be:

```
@staticmethod
    def _combine_lattice(attr_1, attr_2, len_1, len_2):
        """
        Helper function to combine trajectory properties such as site_properties or lattice
        """
        if np.shape(attr_1) == (3, 3) and np.shape(attr_2) == (3, 3):
            attribute = attr_1
            attribute_constant = True
        elif np.ndim(attr_1) == 3 and np.ndim(attr_2) == 3:  # np.shape changed to np.ndim
            attribute = np.concatenate((attr_1, attr_2), axis=0)
            attribute_constant = False
        else:  
            # Deal with case where any of attr_1 (self.lattice) and  attr_1 (trajectory.lattice) is a list of numpy.ndarrays of shape (3, 3)            attribute = [attr_1.copy()] * len_1 if isinstance(attr_1, list) else attr_1.copy()
            attribute.extend([attr_2.copy()] * len_2 if isinstance(attr_2, list) else attr_2.copy())
            attribute_constant = False
        return attribute, attribute_constant
```
What I did was to change `elif np.shape(attr_1) == 3 and np.shape(attr_2) == 3:` to `elif np.ndim(attr_1) == 3 and np.ndim(attr_2) == 3:`.
It seems to work correctly, but I suspect that further tests might be needed.

However I think this is not yet perfect. In the case where attr_1 or attr_2 is a list whereas the other is a numpy.ndarray, then the function will again try to extend a numpy ndarray, which will give the same error as above. My suggestion to correct this problem would to :
- convert both attr_1 and attr_2 to numpy ndarrays of shapes (len_1, 3, 3) and (len_2, 3, 3)
- use np.concatenate((attr_1, attr_2), axis=0) as in the case above
- raise a warning to indicate that the lattice type of the concatated trajectory is different from one of the two initial arrays.

Another possibility would be keep the type of the first trajectory and convert the second to that type...

Hoping this helps (and looking very much forward to reading your solution to this problem(s).
Sylvian.
