### ISSUE TITLE
Running pymatgen 2023.5.31 on Apple M1 MacOS yields incompatible architecture error

### ISSUE THREAD

**Issue by exenGT** [materialsproject/pymatgen#3045]
Running the following test code on Apple M1 MacOS:
```
from mp_api.client import MPRester

api_key = "*****"

with MPRester(api_key) as mpr:
    struct = mpr.get_structure_by_material_id("mp-2534")
```
gives the following error:
```
Traceback (most recent call last):
  File "/Users/jw598/Rafael_project/codes/test.py", line 9, in <module>
    from mp_api.client import MPRester
  File "/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/mp_api/client/__init__.py", line 5, in <module>
    from .core import MPRestError
  File "/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/mp_api/client/core/__init__.py", line 1, in <module>
    from .client import BaseRester, MPRestError
  File "/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/mp_api/client/core/client.py", line 20, in <module>
    from emmet.core.utils import jsanitize
  File "/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/emmet/core/utils.py", line 10, in <module>
    from pymatgen.analysis.graphs import MoleculeGraph
  File "/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/analysis/graphs.py", line 26, in <module>
    from pymatgen.core import Lattice, Molecule, PeriodicSite, Structure
  File "/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/core/__init__.py", line 14, in <module>
    from pymatgen.core.lattice import Lattice as Lattice
  File "/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/core/lattice.py", line 21, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/util/coord.py", line 16, in <module>
    from pymatgen.util import coord_cython as cuc
ImportError: dlopen(/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-darwin.so, 0x0002): tried: '/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-darwin.so' (no such file), '/Users/jw598/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

Operating system is Ventura 13.3.1, Python version is 3.9.16. The code above works with pymatgen 2023.5.10.

**Comment by janosh** [comment]
Could you try a clean re-install?

```sh
pip uninstall -y pymatgen
pip cache purge
pip install pymatgen
```

If that doesn't help, try outside a `conda` env.

```sh
# without a conda env active
python -m venv debug
. ./debug/bin/activate
pip install pymatgen
```

**Comment by exenGT** [comment]
Hi @janosh, I've tried both suggestions, none of them works (the error still persists).

**Comment by janosh** [comment]
Could you post the stack trace from the python `venv`, i.e. the error without `conda`?

**Comment by exenGT** [comment]
Traceback (most recent call last):
  File "/Users/jw598/Rafael_project/codes/test.py", line 9, in <module>
    from mp_api.client import MPRester
  File "/Users/jw598/debug/lib/python3.9/site-packages/mp_api/client/__init__.py", line 5, in <module>
    from .core import MPRestError
  File "/Users/jw598/debug/lib/python3.9/site-packages/mp_api/client/core/__init__.py", line 1, in <module>
    from .client import BaseRester, MPRestError
  File "/Users/jw598/debug/lib/python3.9/site-packages/mp_api/client/core/client.py", line 20, in <module>
    from emmet.core.utils import jsanitize
  File "/Users/jw598/debug/lib/python3.9/site-packages/emmet/core/utils.py", line 10, in <module>
    from pymatgen.analysis.graphs import MoleculeGraph
  File "/Users/jw598/debug/lib/python3.9/site-packages/pymatgen/analysis/graphs.py", line 26, in <module>
    from pymatgen.core import Lattice, Molecule, PeriodicSite, Structure
  File "/Users/jw598/debug/lib/python3.9/site-packages/pymatgen/core/__init__.py", line 14, in <module>
    from pymatgen.core.lattice import Lattice as Lattice
  File "/Users/jw598/debug/lib/python3.9/site-packages/pymatgen/core/lattice.py", line 21, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/Users/jw598/debug/lib/python3.9/site-packages/pymatgen/util/coord.py", line 16, in <module>
    from pymatgen.util import coord_cython as cuc
ImportError: dlopen(/Users/jw598/debug/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-darwin.so, 0x0002): tried: '/Users/jw598/debug/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jw598/debug/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-darwin.so' (no such file), '/Users/jw598/debug/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by janosh** [comment]
Could you try `ARCHFLAGS="-arch arm64" pip install pymatgen --compile --no-cache-dir`?

**Comment by exenGT** [comment]
It works with your command now!
