### ISSUE TITLE
pymatgen.io.vasp.inputs.Potcar can't read file POTCAR.z

### ISSUE THREAD

**Issue by lzuyanghl** [materialsproject/pymatgen#314]
## System

* Pymatgen version: 3.3.5
* Python version: Python 2.7.11 :: Anaconda 2.5.0 (64-bit)
* OS version: Ubuntu 14.04

## Summary

if the format of the POTCAR is gzip, Potcar cannot read it. But zcat and  uncompress can use to 
decompression the file.

## Example code

```python
import os
from pymatgen.io.vasp.inputs import Potcar
import pymatgen.io.vasp as vaspio

os.environ['VASP_PSP_DIR'] = r"/home/vagrant/workspace/potpaw"
Potcar(symbols=['Co', 'Cu'], functional='LDA')
```

## Error message

```
Traceback (most recent call last):
  File "potcar.py", line 9, in <module>
    Potcar(symbols=['Co', 'Cu'], functional='LDA')
  File "/home/vagrant/apps/anaconda2/lib/python2.7/site-packages/pymatgen/io/vasp/inputs.py", line 1610, in __init__
    self.set_symbols(symbols, functional, sym_potcar_map)
  File "/home/vagrant/apps/anaconda2/lib/python2.7/site-packages/pymatgen/io/vasp/inputs.py", line 1690, in set_symbols
    p = PotcarSingle.from_symbol_and_functional(el, functional)
  File "/home/vagrant/apps/anaconda2/lib/python2.7/site-packages/pymatgen/io/vasp/inputs.py", line 1491, in from_symbol_and_functional
    return PotcarSingle.from_file(p)
  File "/home/vagrant/apps/anaconda2/lib/python2.7/site-packages/pymatgen/io/vasp/inputs.py", line 1474, in from_file
    return PotcarSingle(f.read())
  File "/home/vagrant/apps/anaconda2/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/home/vagrant/apps/anaconda2/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/home/vagrant/apps/anaconda2/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

```

**Comment by shyuep** [comment]
Hi there, I am not sure what you mean. The Potcar class definitely supports gzip. Can you post a file for us where this fails so taht we can work on it?

**Comment by lzuyanghl** [comment]
I think the problem is gzip module. [POTCAR.z](https://drive.google.com/file/d/0B7DapXLbWsRKc0ljb3lxWjV3aWM/view?usp=sharing)

**Comment by shyuep** [comment]
Oh, that's a problem with python's gzip class. I don't think it is a bug per se, but rather the Z format is not strictly the same as the gzip format. There's really nothing much we can do on this front.
