### ISSUE TITLE
DummySpecies have recursion issue when calling getattr

### ISSUE THREAD

**Issue by qchempku2017** [materialsproject/pymatgen#3167]
#### Description
After pymatgen update v2023.6.28, a recursion issue happens when using DummySpecies in pytest fixtures. 
Here is the fixture initialization error:
```bash
collecting ... 
test_cofe/test_domain.py:None (test_cofe/test_domain.py)
..\..\venv\lib\site-packages\pluggy\_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
..\..\venv\lib\site-packages\pluggy\_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
..\..\venv\lib\site-packages\_pytest\python.py:262: in pytest_pycollect_makeitem
    return list(collector._genfunctions(name, obj))
..\..\venv\lib\site-packages\_pytest\python.py:489: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
..\..\venv\lib\site-packages\pluggy\_hooks.py:292: in call_extra
    return self(**kwargs)
..\..\venv\lib\site-packages\pluggy\_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
..\..\venv\lib\site-packages\pluggy\_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
..\..\venv\lib\site-packages\_pytest\python.py:148: in pytest_generate_tests
    metafunc.parametrize(*marker.args, **marker.kwargs, _param_mark=marker)
..\..\venv\lib\site-packages\_pytest\python.py:1304: in parametrize
    ids = self._resolve_parameter_set_ids(
..\..\venv\lib\site-packages\_pytest\python.py:1374: in _resolve_parameter_set_ids
    return id_maker.make_unique_parameterset_ids()
..\..\venv\lib\site-packages\_pytest\python.py:966: in make_unique_parameterset_ids
    resolved_ids = list(self._resolve_ids())
..\..\venv\lib\site-packages\_pytest\python.py:991: in _resolve_ids
    yield "-".join(
..\..\venv\lib\site-packages\_pytest\python.py:992: in <genexpr>
    self._idval(val, argname, idx)
..\..\venv\lib\site-packages\_pytest\python.py:1004: in _idval
    idval = self._idval_from_value(val)
..\..\venv\lib\site-packages\_pytest\python.py:1051: in _idval_from_value
    elif isinstance(getattr(val, "__name__", None), str):
..\..\venv\lib\site-packages\pymatgen\core\periodic_table.py:1062: in __getattr__
    return getattr(self._el, attr)
..\..\venv\lib\site-packages\pymatgen\core\periodic_table.py:1062: in __getattr__
    return getattr(self._el, attr)
..\..\venv\lib\site-packages\pymatgen\core\periodic_table.py:1062: in __getattr__
    return getattr(self._el, attr)
E   RecursionError: maximum recursion depth exceeded
!!! Recursion detected (same locals & position)
```

#### Repro
You can reproduce the same error using the following steps:
```python
sp = DummySpecies("XX", oxidation_state=100, spin=2)
getattr(sp, "__name__", None) 
```
And get:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\66422\PycharmProjects\smol\venv\lib\site-packages\pymatgen\core\periodic_table.py", line 1062, in __getattr__
    return getattr(self._el, attr)
  File "C:\Users\66422\PycharmProjects\smol\venv\lib\site-packages\pymatgen\core\periodic_table.py", line 1062, in __getattr__
    return getattr(self._el, attr)
  File "C:\Users\66422\PycharmProjects\smol\venv\lib\site-packages\pymatgen\core\periodic_table.py", line 1062, in __getattr__
    return getattr(self._el, attr)
  [Previous line repeated 995 more times]
RecursionError: maximum recursion depth exceeded.
```

#### Expected behavior
Normally, since DummySpecies does not have an element attribute, any call to non-existing attributes should return None. However, since DummySpecies inherits from Species whose getattr has be overwritten by that of self._el, when called by getattr, DummySpecies would keep looking for self._el recursively, causing error. Therefore, we should consider redefining getattr for DummySpecies instead of simply inheriting from Species.

**Strangely, this issue did not appear in any version before v2023.6.28. We have not figured out why.**

#### Environment

Relevant versions and platform info:

- OS: Windows 11
- Version: >=v2023.6.28

#### Additional context

More context like related issues/PRs.

**Comment by qchempku2017** [comment]
There are two possible solutions:
1, Redefine the getattr of Species as the following:
```python
def __getattr__(self, attr):
    if attr == "_el":
        raise AttributeError
    return getattr(self._el, attr)
```
2, Add
```python
self._el = None
```
to the __init__ function of DummySpecies.

Which one should be better?

**Comment by shyuep** [comment]
Thanks. I just pushed a fix.
