### ISSUE TITLE
ImportError when using abicheck.py with abipy and pymatgen

### ISSUE THREAD

**Issue by emayMTK** [materialsproject/pymatgen#3170]
I'm encountering an issue when trying to use `abicheck.py` with the `abipy` and `pymatgen` libraries in my `abienv` conda environment. Here's the command I'm running and the error I'm facing:

**Command:**

```bash
(abienv) mtk@mtk-HP-EliteBook-x360-1030-G2:~/abipy$ abicheck.py --with-flow
```

**Error :**

```bash
/home/mtk/miniconda3/envs/abienv/bin/abicheck.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
import('pkg_resources').run_script('abipy==0.9.3', 'abicheck.py')
Traceback (most recent call last):
File "/home/mtk/miniconda3/envs/abienv/bin/abicheck.py", line 4, in
import('pkg_resources').run_script('abipy==0.9.3', 'abicheck.py')
File "/home/mtk/miniconda3/envs/abienv/lib/python3.9/site-packages/pkg_resources/init.py", line 722, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/home/mtk/miniconda3/envs/abienv/lib/python3.9/site-packages/pkg_resources/init.py", line 1561, in run_script
exec(code, namespace, namespace)
File "/home/mtk/miniconda3/envs/abienv/lib/python3.9/site-packages/abipy-0.9.3-py3.9.egg/EGG-INFO/scripts/abicheck.py", line 11, in
import abipy.flowtk as flowtk
File "/home/mtk/miniconda3/envs/abienv/lib/python3.9/site-packages/abipy-0.9.3-py3.9.egg/abipy/flowtk/init.py", line 15, in
from .tasks import *
File "/home/mtk/miniconda3/envs/abienv/lib/python3.9/site-packages/abipy-0.9.3-py3.9.egg/abipy/flowtk/tasks.py", line 36, in
from .abitimer import AbinitTimerParser
File "/home/mtk/miniconda3/envs/abienv/lib/python3.9/site-packages/abipy-0.9.3-py3.9.egg/abipy/flowtk/abitimer.py", line 2, in
from pymatgen.io.abinit.abitimer import AbinitTimerParserError, AbinitTimerParser, AbinitTimerSection
ImportError: cannot import name 'AbinitTimerParserError' from 'pymatgen.io.abinit.abitimer' (/home/mtk/miniconda3/envs/abienv/lib/python3.9/site-packages/pymatgen/io/abinit/abitimer.py)
```

It seems that the `AbinitTimerParserError` class is not being imported from the `pymatgen.io.abinit.abitimer` module, causing the `ImportError`. I have already checked that both `abipy` and `pymatgen` are installed in my `abienv` environment.

I have tried updating both `abipy` and `pymatgen` using `conda update`, but the issue persists. I'm using Python 3.9.

Any suggestions on how to resolve this issue would be greatly appreciated. Thank you in advance for your help!

**Comment by janosh** [comment]
@emayMTK https://github.com/materialsproject/pymatgen/pull/3140 was a recent breaking change that renamed some of the `ParseError` subclasses. `AbinitTimerParserError` is now `AbinitTimerParseError` (note the dropped `r`). Looks like this was already addressed in https://github.com/abinit/abipy/commit/704f4eb0b02f3338a441c8c1dc79696db0449b5b by @gmatteo. Once `abipy` makes a new release, your error will be fixed. You can also modify your abipy package in place right now by replacing `AbinitTimerParserError` with `AbinitTimerParseError`.

**Comment by emayMTK** [comment]
Thank you. it worked.
