### ISSUE TITLE
NameError when importing dos from pymatgen.electronic_structure

### ISSUE THREAD

**Issue by schumannj** [materialsproject/pymatgen#3259]
#### Description

When I try to import
```py
from pymatgen.electronic_structure import dos
```

I get:

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pymatgen/electronic_structure/dos.py", line 625, in <module>
    class CompleteDos(Dos):
  File "/usr/local/lib/python3.7/site-packages/pymatgen/electronic_structure/dos.py", line 814, in CompleteDos
    band: OrbitalType = OrbitalType.d,
NameError: name 'OrbitalType' is not defined
```

It is from a previously working script, so I am not sure if there was a change to the version or why it is not working any more.

#### Environment

Relevant versions and platform info:

- OS: Mac (macOS Catalina)
- Version (e.g. v2023.05.10)

**Comment by janosh** [comment]
Your import works for me. Try `pip uninstall pymatgen -y && pip install -U pymatgen` and then run your script again.
