### ISSUE TITLE
can't run unit test

### ISSUE THREAD

**Issue by hlyang1992** [materialsproject/pymatgen#352]
## System

* Pymatgen version: 3.5.0
* Python version: 2.7
* OS version: ubuntu 14.04

## Problem
when run `nosetests` in the pymatgen root directory, the output is:

```
Traceback (most recent call last):
  File "/home/vagrant/opt/anaconda2/bin/nosetests", line 4, in <module>
    from nose import run_exit
  File "/home/vagrant/opt/anaconda2/lib/python2.7/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/home/vagrant/opt/anaconda2/lib/python2.7/site-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/home/vagrant/opt/anaconda2/lib/python2.7/site-packages/nose/config.py", line 9, in <module>
    from nose.plugins.manager import NoPlugins
  File "/home/vagrant/opt/anaconda2/lib/python2.7/site-packages/nose/plugins/__init__.py", line 185, in <module>
    from nose.plugins.manager import *
  File "/home/vagrant/opt/anaconda2/lib/python2.7/site-packages/nose/plugins/manager.py", line 418, in <module>
    import pkg_resources
  File "/home/vagrant/opt/anaconda2/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 25, in <module>
    
  File "/home/vagrant/opt/anaconda2/lib/python2.7/zipfile.py", line 501, in <module>
    class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'

```

**Comment by shyuep** [comment]
Nosetests are run in the root directory whre setup.py is. Not the pymatgen directory.

**Comment by hlyang1992** [comment]
Thank you, but I first run Nosetests in the directory where setup.py, the error is:

```
E
======================================================================
ERROR: Failure: ImportError (No module named coord_utils_cython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/opt/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vagrant/opt/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/opt/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vagrant/space/pymatgen/pymatgen/__init__.py", line 14, in <module>
    from .core import *
  File "/home/vagrant/space/pymatgen/pymatgen/core/__init__.py", line 17, in <module>
    from .structure import Structure, IStructure, Molecule, IMolecule
  File "/home/vagrant/space/pymatgen/pymatgen/core/structure.py", line 40, in <module>
    from pymatgen.core.sites import Site, PeriodicSite
  File "/home/vagrant/space/pymatgen/pymatgen/core/sites.py", line 26, in <module>
    from pymatgen.util.coord_utils import pbc_diff
  File "/home/vagrant/space/pymatgen/pymatgen/util/coord_utils.py", line 25, in <module>
    import pymatgen.util.coord_utils_cython as cuc
ImportError: No module named coord_utils_cython

----------------------------------------------------------------------
Ran 1 test in 0.374s

FAILED (errors=1)
```

**Comment by shyuep** [comment]
You need to run python setup.py develop or install before running the nosetests.
