### ISSUE TITLE
Importing Trajectory from pymatgen.core.trajectory gives an NameError on latest release (2024.2.20)

### ISSUE THREAD

**Issue by v1kko** [materialsproject/pymatgen#3643]
### Python version

3.11

### Pymatgen version

2024.2.20

### Operating system version

Any Linux

### Current behavior

Importing gives a NameError:
```
    from pymatgen.core.trajectory import Trajectory as PymatgenTrajectory
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pymatgen/core/trajectory.py:19: in <module>
    from pymatgen.io.ase import AseAtomsAdaptor
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pymatgen/io/ase.py:44: in <module>
    class MSONAtoms(Atoms, MSONable):
E   NameError: name 'Atoms' is not defined
```

### Expected Behavior

I expect the import to be successful. It works on all versions before 2024.2.20

### Minimal example

```Python
Python 3.11.7 (main, Dec  4 2023, 18:10:11) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymatgen.core.trajectory import Trajectory 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/pymatgen/core/trajectory.py", line 19, in <module>
    from pymatgen.io.ase import AseAtomsAdaptor
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/pymatgen/io/ase.py", line 44, in <module>
    class MSONAtoms(Atoms, MSONable):
                    ^^^^^
NameError: name 'Atoms' is not defined
```
```


### Relevant files to reproduce this bug

_No response_

**Comment by ml-evs** [comment]
See #3644

**Comment by v1kko** [comment]
Thank you for the workaround suggestion!

Closing this as duplicate of #3644
