### ISSUE TITLE
ValueError:dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by yjhao11** [materialsproject/pymatgen#3731]
### Python version

python3.9

### Pymatgen version

2023.12.18

### Operating system version

ubuntu 22.04 LTS

### Current behavior

when I Configure pymatgen and then type pmg config --add PMG_VASP_PSP_DIR /abs/path/to/psp PMG_MAPI_KEY my_api_key , there are some errors.

pmg config --add PMG_VASP_PSP_DIR /home/hyj/soft/atomate/pps my_api_key
Traceback (most recent call last):
  File "/home/hyj/miniconda3/envs/atomate2/bin/pmg", line 5, in <module>
    from pymatgen.cli.pmg import main
  File "/home/hyj/miniconda3/envs/atomate2/lib/python3.9/site-packages/pymatgen/cli/pmg.py", line 12, in <module>
    from pymatgen.cli.pmg_analyze import analyze
  File "/home/hyj/miniconda3/envs/atomate2/lib/python3.9/site-packages/pymatgen/cli/pmg_analyze.py", line 12, in <module>
    from pymatgen.apps.borg.hive import SimpleVaspToComputedEntryDrone, VaspToComputedEntryDrone
  File "/home/hyj/miniconda3/envs/atomate2/lib/python3.9/site-packages/pymatgen/apps/borg/hive.py", line 15, in <module>
    from pymatgen.entries.computed_entries import ComputedEntry, ComputedStructureEntry
  File "/home/hyj/miniconda3/envs/atomate2/lib/python3.9/site-packages/pymatgen/entries/__init__.py", line 16, in <module>
    from pymatgen.core.composition import Composition
  File "/home/hyj/miniconda3/envs/atomate2/lib/python3.9/site-packages/pymatgen/core/__init__.py", line 79, in <module>
    locals().update(SETTINGS)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

How to solve? Thank you very much!

### Expected Behavior

How to solve ? Thank you very much!

**Comment by yjhao11** [comment]
I fixed it.Thank you very much!
