### ISSUE TITLE
Numpy 2.0 incompatability

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3882]
### Python version

3.11

### Pymatgen version

2024.6.10

### Operating system version

Ubuntu

### Current behavior

When doing `pip install pymatgen`, you get `numpy==2.0` right now. This breaks Pymatgen, so we in the short-term we need to pin `pyproject.toml` to have numpy<2 and longer term we need to fix the underlying issues.

```python
from pymatgen.core import Structure
```

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/pymatgen/core/__init__.py", line 13, in <module>
    from pymatgen.core.lattice import Lattice
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/pymatgen/core/lattice.py", line 21, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/pymatgen/util/coord.py", line 15, in <module>
    from pymatgen.util import coord_cython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/pymatgen/core/__init__.py", line 13, in <module>
    from pymatgen.core.lattice import Lattice
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/pymatgen/core/lattice.py", line 21, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/pymatgen/util/coord.py", line 15, in <module>
    from pymatgen.util import coord_cython
  File "pymatgen/util/coord_cython.pyx", line 1, in init pymatgen.util.coord_cython
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

### Expected Behavior

No crash.

**Comment by shyuep** [comment]
Already fixed in the last commit. But there are some issues with CI on windows I am working on.

**Comment by Andrew-S-Rosen** [comment]
Ah, very speedy! I missed that. Thanks for patching!

**Comment by njzjz** [comment]
I noticed that Pymatgen is still built against the old version of NumPy.

https://github.com/materialsproject/pymatgen/blob/2b53fb1cdf08d5022894c0cb4e6960f3c4edcf81/pyproject.toml#L4-L5

In https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice, it's recommended built against `numpy>=2.0.0rc1`.
