### ISSUE TITLE
Installation failed using self-forked version

### ISSUE THREAD

**Issue by jinlhr542** [materialsproject/pymatgen#3928]
### Python version

3.11

### Pymatgen version

2024.06.10

### Operating system version

Mac

### Current behavior

![image](https://github.com/user-attachments/assets/f932b172-fdd8-4ba6-955e-938b2210c03b)
![image](https://github.com/user-attachments/assets/bb4a4c91-4fad-40f8-8030-2300a2d47473)
I am trying to contribute to pymatgen but as you can see when I install my forked pymatgen by 'pip install .' The packages are not installed

### Expected Behavior

\

**Comment by DanielYang59** [comment]
I'm guess you might have a `pymatgen.py` shadowing the real `pymatgen`, let me know if it's not the case :)

**Comment by jsukpark** [comment]
Same issue here. Python 3.12, Pymatgen version 2024.6.10, CentOS Linux 7. Trying to run

```
from pymatgen.io.pwscf import PWInput
```

after installing my forked pymatgen gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pymatgen.io'
```

Tried using both `pip install .` in the top directory and `pip install -U git+https://github.com/jsukpark/pymatgen` for installing my forked pymatgen, same issue happens in both.

**Comment by DanielYang59** [comment]
Hi @jsukpark thanks for providing the information. I just tried to clone your fork and things seem to work fine on my side. 

Can you post the output of `pip install .` so that I could have a closer look?

**Comment by jsukpark** [comment]
```
(torch-v2) login2.frontera(1027)$ pip install .
Processing /work2/08542/epark/frontera/pymatgen
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: matplotlib>=3.8 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (3.9.0)
Requirement already satisfied: monty>=2024.5.24 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (2024.7.12)
Requirement already satisfied: networkx>=2.2 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (3.3)
Requirement already satisfied: palettable>=3.1.1 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (3.3.3)
Requirement already satisfied: pandas>=2 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (2.2.2)
Requirement already satisfied: plotly>=4.5.0 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (5.22.0)
Requirement already satisfied: pybtex>=0.24.0 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (0.24.0)
Requirement already satisfied: requests>=2.32 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (2.32.2)
Requirement already satisfied: ruamel.yaml>=0.17.0 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (0.18.6)
Requirement already satisfied: scipy>=1.13.0 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (1.13.0)
Requirement already satisfied: spglib>=2.5.0 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (2.5.0)
Requirement already satisfied: sympy>=1.2 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (1.12)
Requirement already satisfied: tabulate>=0.9 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (0.9.0)
Requirement already satisfied: tqdm>=4.60 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (4.66.4)
Requirement already satisfied: uncertainties>=3.1.4 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (3.1.7)
Requirement already satisfied: joblib>=1 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (1.4.2)
Requirement already satisfied: numpy>=1.25.0 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pymatgen==2024.6.10) (1.26.4)
Requirement already satisfied: contourpy>=1.0.1 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen==2024.6.10) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen==2024.6.10) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen==2024.6.10) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen==2024.6.10) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen==2024.6.10) (24.0)
Requirement already satisfied: pillow>=8 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen==2024.6.10) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen==2024.6.10) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen==2024.6.10) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pandas>=2->pymatgen==2024.6.10) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pandas>=2->pymatgen==2024.6.10) (2024.1)
Requirement already satisfied: tenacity>=6.2.0 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from plotly>=4.5.0->pymatgen==2024.6.10) (8.3.0)
Requirement already satisfied: PyYAML>=3.01 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pybtex>=0.24.0->pymatgen==2024.6.10) (6.0.1)
Requirement already satisfied: latexcodec>=1.0.4 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pybtex>=0.24.0->pymatgen==2024.6.10) (3.0.0)
Requirement already satisfied: six in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from pybtex>=0.24.0->pymatgen==2024.6.10) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from requests>=2.32->pymatgen==2024.6.10) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from requests>=2.32->pymatgen==2024.6.10) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from requests>=2.32->pymatgen==2024.6.10) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from requests>=2.32->pymatgen==2024.6.10) (2024.2.2)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from ruamel.yaml>=0.17.0->pymatgen==2024.6.10) (0.2.8)
Requirement already satisfied: mpmath>=0.19 in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from sympy>=1.2->pymatgen==2024.6.10) (1.3.0)
Requirement already satisfied: future in /work2/08542/epark/frontera/miniconda3/envs/torch-v2/lib/python3.12/site-packages (from uncertainties>=3.1.4->pymatgen==2024.6.10) (1.0.0)
Building wheels for collected packages: pymatgen
  Building wheel for pymatgen (pyproject.toml) ... done
  Created wheel for pymatgen: filename=pymatgen-2024.6.10-cp312-cp312-linux_x86_64.whl size=337779 sha256=7d284a9afa36dc9b5efab55eb2491005147c89c38d83bfdf16c1ce10134c3109
  Stored in directory: /tmp/pip-ephem-wheel-cache-wepbrq2c/wheels/f8/0d/31/8029a58ece5c6f8f5e5e16824abde28f5dd1efc7d9d479d03a
Successfully built pymatgen
Installing collected packages: pymatgen
Successfully installed pymatgen-2024.6.10
(torch-v2) login2.frontera(1028)$ python3
Python 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:46:43) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymatgen.io.pwscf import PWInput
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pymatgen.io'
>>> 
```

**Comment by shyuep** [comment]
My guess would be that the pip and the python are two different envs. Please create a *fresh* virtual env and try again.

**Comment by DanielYang59** [comment]
I was able to reproduce this issue from the master branch, it appears after moving to the src layout, the wheel is build with incomplete package, I'm trying to fix this.
```
> python3 -m build --wheel
......
creating '/Users/yang/temporary/pymatgen/dist/.tmp-z71e47nv/pymatgen-2024.6.10-cp312-cp312-macosx_11_0_arm64.whl' and adding 'build/bdist.macosx-11.1-arm64/wheel' to it
adding 'pymatgen/dao.py'
adding 'pymatgen/py.typed'
adding 'pymatgen/optimization/linear_assignment.cpython-312-darwin.so'
adding 'pymatgen/optimization/linear_assignment.pyx'
adding 'pymatgen/optimization/neighbors.cpython-312-darwin.so'
adding 'pymatgen/optimization/neighbors.pyx'
adding 'pymatgen/util/coord_cython.cpython-312-darwin.so'
adding 'pymatgen/util/coord_cython.pyx'
adding 'pymatgen-2024.6.10.dist-info/LICENSE'
adding 'pymatgen-2024.6.10.dist-info/METADATA'
adding 'pymatgen-2024.6.10.dist-info/WHEEL'
adding 'pymatgen-2024.6.10.dist-info/entry_points.txt'
adding 'pymatgen-2024.6.10.dist-info/top_level.txt'
adding 'pymatgen-2024.6.10.dist-info/RECORD'
removing build/bdist.macosx-11.1-arm64/wheel
Successfully built pymatgen-2024.6.10-cp312-cp312-macosx_11_0_arm64.whl
```

**Comment by jsukpark** [comment]
I just confirmed that after pulling Daniel's hotfix to my fork, things are working fine on my end as well! Thanks for addressing this!

**Comment by DanielYang59** [comment]
@jsukpark Thanks for confirming! Happy coding!

**Comment by DanielYang59** [comment]
@janosh Sorry I forgot to include a "to fix" (or similar) keyword in the PR, but we can close this now.
