### ISSUE TITLE
pymatgen fails to load MPRester

### ISSUE THREAD

**Issue by jjkas** [materialsproject/pymatgen#4077]
### Python version

Python 3.12.5

### Pymatgen version

2024.9.17

### Operating system version

Linux Mint V22, windows10 64 bit, 

### Current behavior

>>> from pymatgen.ext.matproj import MPRester

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/home/jjkas/miniconda3/envs/Corvus/lib/python3.12/site-packages/pymatgen/ext/matproj.py", line 25, in <module>
    from pymatgen.core import SETTINGS
  File "/home/jjkas/miniconda3/envs/Corvus/lib/python3.12/site-packages/pymatgen/core/__init__.py", line 13, in <module>
    from pymatgen.core.lattice import Lattice
  File "/home/jjkas/miniconda3/envs/Corvus/lib/python3.12/site-packages/pymatgen/core/lattice.py", line 19, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/jjkas/miniconda3/envs/Corvus/lib/python3.12/site-packages/pymatgen/util/coord.py", line 15, in <module>
    from pymatgen.util import coord_cython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jjkas/miniconda3/envs/Corvus/lib/python3.12/site-packages/pymatgen/ext/matproj.py", line 25, in <module>
    from pymatgen.core import SETTINGS
  File "/home/jjkas/miniconda3/envs/Corvus/lib/python3.12/site-packages/pymatgen/core/__init__.py", line 13, in <module>
    from pymatgen.core.lattice import Lattice
  File "/home/jjkas/miniconda3/envs/Corvus/lib/python3.12/site-packages/pymatgen/core/lattice.py", line 19, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/jjkas/miniconda3/envs/Corvus/lib/python3.12/site-packages/pymatgen/util/coord.py", line 15, in <module>
    from pymatgen.util import coord_cython
  File "pymatgen/util/coord_cython.pyx", line 1, in init pymatgen.util.coord_cython
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

### Expected Behavior

Since pymatgen change log states explicit fixes for version v2024.9.10, I would expect its requirements also to work with numpy >2.0. Not sure if this is a bug, but perhaps changing installation via pypi to require numpy<2.0 would be a good idea?
Notes: 
1. Seems to be due to requirement of emmet-core of numpy<2.0.
1. Works on mac m2 with the same versions of python/pymatgen.

### Minimal example

```Python
>> from pymatgen.ext.matproj import MPRester
fails with numpy 2.1.1
works with numpy 1.26.
```

**Comment by shyuep** [comment]
Pls state whether you are using MPRester basic or the mp-api version. If it is the mp-api version, then you will have to post this in that repo. If it is basic, then let us know.

**Comment by jjkas** [comment]
It happens with both, but it's really a problem with pymatgen rather than mp-api. If numpy>2.0 is installed, the following two commands both fail:

>> from pymatgen.ext.matproj import MPRester
>> from mp_api.client import MPRester

However, the problem in general is not a problem for mp-api since there is a requirement there to install numpy<2.0. Thus if both mp-api and pymatgen are pip installed, both work, since mp-api will downgrade numpy to <2.0, and pymatgen does not require numpy>2.0. If only pymatgen is installed in a clean environment, numpy does not have the <2.0 requirement and MPRester fails.

**Comment by DanielYang59** [comment]
@jjkas I cannot reproduce this issue. Can you please confirm your `pymatgen` version? I would expect version `[v2024.9.10](https://github.com/materialsproject/pymatgen/releases/tag/v2024.9.10)` and afterwards to fully support numpy 2.

```python
import numpy as np
from pymatgen.ext.matproj import MPRester
import pkg_resources


print("NumPy version:", np.__version__)
print("pymatgen version:", pkg_resources.get_distribution("pymatgen").version)
print(dir(MPRester))
```

**Comment by jjkas** [comment]
I'm now having trouble reproducing the problem myself. I'll see if I can get it to occur again.

**Comment by DanielYang59** [comment]
Cool, let me know if you found anything.

>  NumPy version: 1.26.4

Note you appear to be running numpy 1.26 while the original issue was reported on numpy 2.x, so please make sure you have the correct version of numpy installed.

I tried to run both numpy 1.26 and numpy 2.1 on my Windows machine and cannot reproduce this.
