### ISSUE TITLE
pmg plot --dos ... errs in matplotlib call

### ISSUE THREAD

**Issue by yantar92** [materialsproject/pymatgen#4108]
### Python version

3.12.7

### Pymatgen version

2024.10.3

### Current behavior

```bash
 pmg plot -d vasprun.xml --out_file dos.png
```
yields

```bash
Traceback (most recent call last):
  File "/home/yantar92/Downloads/Nio.DOS/.venv/bin/pmg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yantar92/Downloads/Nio.DOS/.venv/lib/python3.12/site-packages/pymatgen/cli/pmg.py", line 448, in main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/home/yantar92/Downloads/Nio.DOS/.venv/lib/python3.12/site-packages/pymatgen/cli/pmg_plot.py", line 107, in plot
    plt.savefig(args.out_file)
    ^^^^^^^^^^^
AttributeError: 'Axes' object has no attribute 'savefig'
```

### Expected Behavior

The DOS plot is generated.

### Minimal example

```Python
pip install matplotlib
cd /path/to/vasp/results
pmg plot -d vasprun.xml --out_file dos.png

```
I suspect that my Matplotlib Version: 3.9.2 might have changes in the API.

**Comment by DanielYang59** [comment]
Thanks for reporting this, I would fix this
