### ISSUE TITLE
Structure.merge_sites fails when selective_dynamics is property present

### ISSUE THREAD

**Issue by yantar92** [materialsproject/pymatgen#4197]
### Python version

Python 3.12.7

### Pymatgen version

Version: 2024.10.22

### Current behavior

Error is thrown when I try to run merge_sites.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yantar92/.venv/lib/python3.12/site-packages/pymatgen/core/structure.py", line 4604, in merge_sites
    if props[key] is not None and self[i].properties[key] != props[key]:
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Expected Behavior

merge_sites works without errors :)

### Minimal example

```Python
import pymatgen.core as pmg
str1 = pmg.Structure.from_file('POSCAR1')
str2 = pmg.Structure.from_file('POSCAR2')
merge = str1.copy()
for site in str2:
    merge.append(site.species, site.frac_coords, properties=site.properties)
merge.merge_sites(mode='average')
```

### Relevant files to reproduce this bug

[POSCAR2.gz](https://github.com/user-attachments/files/17900367/POSCAR2.gz)
[POSCAR1.gz](https://github.com/user-attachments/files/17900368/POSCAR1.gz)

**Comment by DanielYang59** [comment]
Thanks for reporting and for including a code snippet again, I would take care of this
