### ISSUE TITLE
Error when using BSPlotter under python 3.6.2

### ISSUE THREAD

**Issue by Hugo-Leung** [materialsproject/pymatgen#745]
## System

* Pymatgen version: <2017.06.08>
* Python version: <3.6.2>
* OS version: <SL7.3> 

## Summary
I got an error when I try to plot the projected band structure 

## Example code

```import matplotlib 
matplotlib.use("pdf")
from pymatgen.io.vasp import BSVasprun
from pymatgen.electronic_structure.plotter import BSPlotterProjected

v=BSVasprun("vasprun.xml",parse_projected_eigen=True)
bs=v.get_band_structure(kpoints_filename="KPOINTS",line_mode=True)

plt=BSPlotterProjected(bs)
fig=plt.get_plot()
fig.savefig("bandstructure.pdf")

dic={"Ga":["s"]}
fig=plt.get_projected_plots_dots(dic)
fig.savefig("Ga_s.pdf")

matplotlib.pyplot.close("all")
# Example code generating error
```

## Error message

```
/opt/anaconda3/lib/python3.6/site-packages/matplotlib/tight_layout.py:226: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/mathtext.py", line 2517, in parse
    result = self._expression.parseString(s)
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1216, in parseString
    raise exc
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1206, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1072, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 2801, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1072, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 2544, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1072, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 2970, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 2923, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1072, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 2527, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1098, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 819, in wrapper
    ret = func(*args[limit[0]:])
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/mathtext.py", line 2588, in math_string
    return self._math_expression.parseString(toks[0][1:-1])
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1216, in parseString
    raise exc
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1206, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1072, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 2801, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1072, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 2923, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1072, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 2801, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1072, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 2658, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 1098, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/opt/anaconda3/lib/python3.6/site-packages/pyparsing.py", line 819, in wrapper
    ret = func(*args[limit[0]:])
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/mathtext.py", line 2694, in unknown_symbol
    raise ParseFatalException(s, loc, "Unknown symbol: %s" % c)
pyparsing.ParseFatalException: Unknown symbol: \ (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hleung/vasptools/bandstructure.py", line 11, in <module>
    fig.savefig("bandstructure.pdf")
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1573, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2252, in print_figure
    **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 2527, in print_pdf
    self.figure.draw(renderer)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1144, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2426, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1150, in draw
    self.label.draw(renderer)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 802, in draw
    ismath=ismath, mtext=mtext)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 1953, in draw_text
    return self.draw_mathtext(gc, x, y, s, prop, angle)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 1779, in draw_mathtext
    self.mathtext_parser.parse(s, 72, prop)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/mathtext.py", line 3286, in parse
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/opt/anaconda3/lib/python3.6/site-packages/matplotlib/mathtext.py", line 2523, in parse
    six.text_type(err)]))
ValueError:
\\mathrm{Wave\ Vector}
^
Unknown symbol: \ (at char 0), (line:1, col:1)

# Error message
```

## Suggested solution 
I've read that it could be due to the `r` in `plt.xlabel(r'$\mathrm{Wave\ Vector}$', fontsize=30)` in the BSPlotter class.

**Comment by shyuep** [comment]
I think this has been fixed in recent versions. Pls upgrade your pymatgen to 2017.7.21 and try again.

**Comment by shyuep** [comment]
Closing this issue for now. Pls reopen if you still encounter the same issue in more recent versions.
