### ISSUE TITLE
An Odd ImportError

### ISSUE THREAD

**Issue by jic198** [materialsproject/pymatgen#959]
I have been trying to run pymatgen in Python 3 but always getting an odd ImportError. I also installed pymatgen in Python 2, but that one is fine. I have tried:
1. pip install pymatgen
2. git clone pymatgen and pip install .
3. reinstall scipy
But none of the above fix the error. Any idea why it happens? 
Thanks

## System

* Pymatgen version: 2017.12.8
* Python version: 3.6
* OS version: OS X EI Capitan 

## Example code

```python
pmg -h
```

## Error message

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pmg", line 11, in <module>
    load_entry_point('pymatgen', 'console_scripts', 'pmg')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/Jianli/GDrive/repos/pymatgen/pymatgen/__init__.py", line 54, in <module>
    from pymatgen.core import *
  File "/Users/Jianli/GDrive/repos/pymatgen/pymatgen/core/__init__.py", line 7, in <module>
    from .periodic_table import Element, Specie, DummySpecie
  File "/Users/Jianli/GDrive/repos/pymatgen/pymatgen/core/periodic_table.py", line 14, in <module>
    from pymatgen.core.units import Mass, Length, unitized, FloatWithUnit, Unit, \
  File "/Users/Jianli/GDrive/repos/pymatgen/pymatgen/core/units.py", line 16, in <module>
    import scipy.constants as const
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/__init__.py", line 118, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/_lib/_ccallback_c.cpython-36m-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/_lib/_ccallback_c.cpython-36m-darwin.so: mach-o, but wrong architecture
```

**Comment by shyuep** [comment]
This is clearly an issue with your scipy installation

Shyue Ping
________________________________

**Comment by jic198** [comment]
Thanks for the quick reply.
I am aware of that. I reinstalled it, but still couldn’t fix it.
Uninstall:
pip uninstall scipy
Install:
pip install scipy

Should I try some other ways to reinstall scipy?

**Comment by shyuep** [comment]
Try using the conda way of installing.

Shyue Ping
________________________________

**Comment by jic198** [comment]
That got it to work. Thanks:)

Jianli
